// app2/tests/copy-build.js — inline content/copy/*.csv into content/copy/index.js, and the keys
// sheet content/keys.csv (M50) into content/keys.js (the engine never fetches at runtime).
// Drift-checked like the public pages:
//   node app2/tests/copy-build.js --write    regenerate index.js
//   node app2/tests/copy-build.js            check mode (npm run check): fail if index.js differs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCsv } from '../content/copy/csv.js';

const here = dirname(fileURLToPath(import.meta.url));
export const COPY_DIR = resolve(here, '..', 'content', 'copy');
export const FILES = ['lessons.csv', 'goals.csv', 'modules.csv', 'site.csv', 'micro.csv', 'drills.csv', 'drill_goals.csv'];
export const HEADERS = {
  'lessons.csv': ['id', 'module', 'order', 'title', 'brief', 'closing', 'wow', 'convention_line', 'mac_note', 'story_beat'],
  'goals.csv': ['lesson_id', 'goal_index', 'text', 'teach', 'why', 'hint_stuck'],
  'modules.csv': ['id', 'name', 'objective', 'story_beat', 'page_name'],
  'site.csv': ['key', 'text'],
  'micro.csv': ['id', 'prompt', 'teach'],   // one row per micro-drill (C2 Run 4): the due-today prompt and its one-line teach
  'drills.csv': ['id', 'title', 'task'],   // one row per drill (R8, M1): the catalog title and the task line
  'drill_goals.csv': ['drill_id', 'kind', 'index', 'text'],   // a drill's goal lines (kind goal), its end-state lines (end) and its what-if line (why)
};
/** Sheets an older copy folder may not carry yet: a missing one reads as empty. */
const OPTIONAL = new Set(['micro.csv', 'drills.csv', 'drill_goals.csv']);

/** Read the copy CSVs from `dir` into the COPY shape. Throws on a header mismatch. */
export function readCopyDir(dir = COPY_DIR) {
  const out = { lessons: {}, goals: {}, modules: {}, site: {}, micro: {}, drills: {}, drillGoals: {}, order: [] };
  for (const f of FILES) {
    const p = join(dir, f);
    if (!existsSync(p)) { if (OPTIONAL.has(f)) continue; throw new Error('missing ' + p); }   // micro.csv arrived with Run 4, the drill sheets with R8; an older copy folder still reads
    const { header, rows } = parseCsv(readFileSync(p, 'utf8'));
    const want = HEADERS[f];
    if (header.join(',') !== want.join(',')) throw new Error(`${f}: header must be "${want.join(',')}" (got "${header.join(',')}")`);
    if (f === 'lessons.csv') for (const r of rows) { out.lessons[r.id] = r; out.order.push(r.id); }
    else if (f === 'goals.csv') for (const r of rows) { (out.goals[r.lesson_id] = out.goals[r.lesson_id] || []).push(r); }
    else if (f === 'modules.csv') for (const r of rows) out.modules[r.id] = r;
    else if (f === 'micro.csv') for (const r of rows) out.micro[r.id] = r;
    else if (f === 'drills.csv') for (const r of rows) out.drills[r.id] = r;
    else if (f === 'drill_goals.csv') for (const r of rows) (out.drillGoals[r.drill_id] = out.drillGoals[r.drill_id] || []).push(r);
    else for (const r of rows) out.site[r.key] = r.text;
  }
  return out;
}

export function renderIndex(copy) {
  const body = JSON.stringify({ lessons: copy.lessons, goals: copy.goals, modules: copy.modules, site: copy.site, micro: copy.micro || {}, drills: copy.drills || {}, drillGoals: copy.drillGoals || {} }, null, 1);
  return `// app2/content/copy/index.js — GENERATED by tests/copy-build.js from content/copy/*.csv. Do not edit by hand;
// edit the CSVs (or import Wolf's with tests/copy-import.js) and run \`npm run check\`, which regenerates this file.
/* eslint-disable */
export const COPY = ${body};
`;
}

/** The keys sheet (M50): one row per key the course uses. Its header, in order. */
export const KEYS_CSV = resolve(here, '..', 'content', 'keys.csv');
export const KEYS_HEADER = ['id', 'command', 'group', 'category', 'win', 'ribbon', 'legacy', 'mac', 'mac_note', 'lesson', 'chapter', 'alternatives', 'what', 'concept', 'note'];
/** Read keys.csv into its rows. Throws on a header mismatch. */
export function readKeys(path = KEYS_CSV) {
  const { header, rows } = parseCsv(readFileSync(path, 'utf8'));
  if (header.join(',') !== KEYS_HEADER.join(',')) throw new Error(`keys.csv: header must be "${KEYS_HEADER.join(',')}" (got "${header.join(',')}")`);
  return rows;
}
export function renderKeys(rows) {
  return `// app2/content/keys.js — GENERATED by tests/copy-build.js from content/keys.csv (M50). Do not edit by hand;
// edit the sheet and run \`node app2/tests/copy-build.js --write\`.
/* eslint-disable */
export const KEYS = ${JSON.stringify(rows, null, 1)};
`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const write = process.argv.includes('--write');
  const target = join(COPY_DIR, 'index.js');
  const text = renderIndex(readCopyDir());
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  const keysTarget = resolve(here, '..', 'content', 'keys.js');
  const keysText = renderKeys(readKeys());
  const keysNow = existsSync(keysTarget) ? readFileSync(keysTarget, 'utf8') : '';
  if (write) { writeFileSync(target, text); writeFileSync(keysTarget, keysText); console.log('copy inlined: content/copy/index.js and content/keys.js'); }
  else if (current !== text) { console.error('CHECK FAILED: content/copy/index.js is out of date — run: node app2/tests/copy-build.js --write'); process.exit(1); }
  else if (keysNow !== keysText) { console.error('CHECK FAILED: content/keys.js is out of date — run: node app2/tests/copy-build.js --write'); process.exit(1); }
  else console.log('copy ok: content/copy/index.js and content/keys.js match the sheets');
}
