// app2/tests/copy-sync.js — the copy layer's build step (C2 Run 3).
//   node app2/tests/copy-sync.js            drift check: chapter1.js must be what chapter1.csv generates (run-checks calls this)
//   node app2/tests/copy-sync.js --write    regenerate app2/content/copy/chapter1.js from the CSV
//   node app2/tests/copy-sync.js --seed     add a draft row for every learner-facing string of the module lessons
//                                           (1.3 on), the module beats and the micro-drills that has no row yet, then --write
// The CSV is RFC 4180: a field with a comma, a quote or a newline is quoted, quotes doubled.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const CSV = join(here, '..', 'content', 'copy', 'chapter1.csv');
const JS = join(here, '..', 'content', 'copy', 'chapter1.js');
const args = new Set(process.argv.slice(2));

export function parseCsv(text) {
  const rows = []; let row = [], field = '', q = false, i = 0;
  const s = String(text).replace(/^﻿/, '');
  while (i < s.length) {
    const ch = s[i];
    if (q) { if (ch === '"') { if (s[i + 1] === '"') { field += '"'; i += 2; continue; } q = false; i++; continue; } field += ch; i++; continue; }
    if (ch === '"') { q = true; i++; continue; }
    if (ch === ',') { row.push(field); field = ''; i++; continue; }
    if (ch === '\r') { i++; continue; }
    if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; i++; continue; }
    field += ch; i++;
  }
  if (field !== '' || row.length) { row.push(field); rows.push(row); }
  return rows.filter(r => r.length > 1 || (r.length === 1 && r[0] !== ''));
}
const csvField = v => { const t = String(v == null ? '' : v); return /[",\n\r]/.test(t) ? '"' + t.replace(/"/g, '""') + '"' : t; };
export function toCsv(rows) { return ['id,field,text,draft', ...rows.map(r => [r.id, r.field, r.text, r.draft ? 'y' : ''].map(csvField).join(','))].join('\n') + '\n'; }

export function readRows() {
  const rows = parseCsv(readFileSync(CSV, 'utf8'));
  const head = rows.shift() || [];
  if (head.slice(0, 4).join(',') !== 'id,field,text,draft') throw new Error('copy/chapter1.csv: the header must be id,field,text,draft');
  return rows.map(r => ({ id: r[0], field: r[1], text: r[2] == null ? '' : r[2], draft: /^(y|yes|true|1|draft)$/i.test(String(r[3] || '').trim()) }));
}
export function generate(rows) {
  const body = rows.map(r => '  ' + JSON.stringify([r.id, r.field, r.text, r.draft ? 1 : 0]) + ',').join('\n');
  return '// GENERATED by app2/tests/copy-sync.js from app2/content/copy/chapter1.csv — do not edit by hand.\n// [id, field, text, draft]\nexport const COPY = [\n' + body + (body ? '\n' : '') + '];\n';
}

/** The learner-facing strings of a lesson as copy rows, in document order. */
export function lessonStrings(l) {
  const out = [];
  const add = (field, text) => { if (typeof text === 'string' && text.trim()) out.push({ id: l.id, field, text }); };
  add('title', l.title); add('brief', l.brief);
  for (const g of l.goals || []) { add(`goal.${g.id}.text`, g.text); if (g.teach) add(`goal.${g.id}.teach`, g.teach); }
  (l.closing || []).forEach((c, i) => add(`closing.${i + 1}`, c));
  (l.endState || []).forEach((e, i) => add(`endState.${i + 1}`, e.text));
  return out;
}

async function seed(rows) {
  const { LESSONS_RAW } = await import('../content/index.js');
  const { MODULE_BEATS } = await import('../app/beats.js');
  const { MICRO } = await import('../app/schedule.js');
  const have = new Set(rows.map(r => r.id + '\u0000' + r.field));
  const added = [];
  const put = (id, field, text) => { const k = id + '\u0000' + field; if (have.has(k) || typeof text !== 'string' || !text.trim()) return; have.add(k); added.push({ id, field, text, draft: true }); };
  const MODULES = ['enter-edit-copy-fill', 'structure', 'format', 'formulas', 'present-and-audit'];
  for (const l of LESSONS_RAW) if (l.workbook && MODULES.includes(l.module)) for (const r of lessonStrings(l)) put(r.id, r.field, r.text);
  for (const m of MODULES) { const b = MODULE_BEATS[m]; if (b) for (const f of ['eyebrow', 'title', 'body']) put('beat/' + m, f, b[f]); }
  for (const id in MICRO) { const m = MICRO[id]; put('micro/' + id, 'title', m.title); put('micro/' + id, 'task', m.task); for (const g of m.goals || []) put('micro/' + id, `goal.${g.id}.text`, g.text); }
  return added;
}

const rows = readRows();
if (args.has('--seed')) {
  const added = await seed(rows);
  const all = rows.concat(added);
  writeFileSync(CSV, toCsv(all)); writeFileSync(JS, generate(all));
  console.log(`copy-sync: ${added.length} draft rows seeded (${all.length} rows), chapter1.js written`);
} else if (args.has('--write')) {
  writeFileSync(JS, generate(rows));
  console.log(`copy-sync: chapter1.js written (${rows.length} rows)`);
} else {
  const want = generate(rows), have = readFileSync(JS, 'utf8');
  if (want !== have) { console.error('copy-sync: app2/content/copy/chapter1.js is stale — run: node app2/tests/copy-sync.js --write'); process.exit(1); }
  console.log(`copy ok: ${rows.length} rows, chapter1.js current`);
}
