// app2/tests/copy-build.js — inline content/copy/*.csv into content/copy/index.js (the engine
// never fetches at runtime). Drift-checked like the public pages:
//   node app2/tests/copy-build.js --write    regenerate index.js
//   node app2/tests/copy-build.js            check mode (npm run check): fail if index.js differs
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseCsv } from '../content/copy/csv.js';

const here = dirname(fileURLToPath(import.meta.url));
export const COPY_DIR = resolve(here, '..', 'content', 'copy');
export const FILES = ['lessons.csv', 'goals.csv', 'modules.csv', 'site.csv', 'micro.csv'];
export const HEADERS = {
  'lessons.csv': ['id', 'module', 'order', 'title', 'brief', 'closing', 'wow', 'convention_line', 'mac_note', 'story_beat'],
  'goals.csv': ['lesson_id', 'goal_index', 'text', 'teach', 'why', 'hint_stuck'],
  'modules.csv': ['id', 'name', 'objective', 'story_beat', 'page_name'],
  'site.csv': ['key', 'text'],
  'micro.csv': ['id', 'prompt', 'teach'],   // one row per micro-drill (C2 Run 4): the due-today prompt and its one-line teach
};

/** Read the four CSVs from `dir` into the COPY shape. Throws on a header mismatch. */
export function readCopyDir(dir = COPY_DIR) {
  const out = { lessons: {}, goals: {}, modules: {}, site: {}, micro: {}, order: [] };
  for (const f of FILES) {
    const p = join(dir, f);
    if (!existsSync(p)) { if (f === 'micro.csv') continue; throw new Error('missing ' + p); }   // micro.csv arrives with Run 4; an older copy folder still reads
    const { header, rows } = parseCsv(readFileSync(p, 'utf8'));
    const want = HEADERS[f];
    if (header.join(',') !== want.join(',')) throw new Error(`${f}: header must be "${want.join(',')}" (got "${header.join(',')}")`);
    if (f === 'lessons.csv') for (const r of rows) { out.lessons[r.id] = r; out.order.push(r.id); }
    else if (f === 'goals.csv') for (const r of rows) { (out.goals[r.lesson_id] = out.goals[r.lesson_id] || []).push(r); }
    else if (f === 'modules.csv') for (const r of rows) out.modules[r.id] = r;
    else if (f === 'micro.csv') for (const r of rows) out.micro[r.id] = r;
    else for (const r of rows) out.site[r.key] = r.text;
  }
  return out;
}

export function renderIndex(copy) {
  const body = JSON.stringify({ lessons: copy.lessons, goals: copy.goals, modules: copy.modules, site: copy.site, micro: copy.micro || {} }, null, 1);
  return `// app2/content/copy/index.js — GENERATED by tests/copy-build.js from content/copy/*.csv. Do not edit by hand;
// edit the CSVs (or import Wolf's with tests/copy-import.js) and run \`npm run check\`, which regenerates this file.
/* eslint-disable */
export const COPY = ${body};
`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const write = process.argv.includes('--write');
  const target = join(COPY_DIR, 'index.js');
  const text = renderIndex(readCopyDir());
  const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
  if (write) { writeFileSync(target, text); console.log('copy inlined: content/copy/index.js'); }
  else if (current !== text) { console.error('CHECK FAILED: content/copy/index.js is out of date — run: node app2/tests/copy-build.js --write'); process.exit(1); }
  else console.log('copy ok: content/copy/index.js matches the CSVs');
}
