-- SEED CLEAR (generated by dev/seed-field.js) — removes EVERY seed row.
-- Run this at launch. Seed ids are namespaced (5eed…) so nothing real matches.
begin;
-- the runs table carries a runs_guard() trigger (anti-cheat: rejects rows that don't come
-- through the app). Seeding is exactly that, on purpose — run the transaction with triggers
-- off (postgres/service role only; also skips FK triggers, which our namespaced ids satisfy).
set local session_replication_role = replica;
delete from public.runs         where user_id::text like '5eed0000-%';
delete from public.team_members where user_id::text like '5eed0000-%';
delete from public.teams        where id::text      like '5eedde5c-%';
delete from public.profiles     where id::text      like '5eed0000-%';
delete from auth.users          where id::text      like '5eed0000-%';
commit;
