-- SEED CLEAR (generated by dev/seed-field.js) — removes EVERY seed row.
-- Run this at launch. Seed ids are namespaced (5eed…) so nothing real matches.
begin;
delete from public.runs         where user_id::text like '5eed0000-%';
delete from public.team_members where user_id::text like '5eed0000-%';
delete from public.teams        where id::text      like '5eedde5c-%';
delete from public.profiles     where id::text      like '5eed0000-%';
delete from auth.users          where id::text      like '5eed0000-%';
commit;
