// app2/content/copy/index.js — GENERATED by tests/copy-build.js from content/copy/*.csv. Do not edit by hand;
// edit the CSVs (or import Wolf's with tests/copy-import.js) and run `npm run check`, which regenerates this file.
/* eslint-disable */
export const COPY = {
 "lessons": {
  "inherited-workbook": {
   "id": "inherited-workbook",
   "module": "open-and-set-up",
   "order": "1.1.1",
   "title": "The workbook management sent",
   "brief": "Management sent the Austin cluster’s site feed, and it arrived the way inherited files do: a tab still called Sheet2, a dead half-export, no page for the report. First get to the bottom of the feed the slow way and the fast way, on your own clock. Then tidy the file, because the tab names you set are the names every reference will carry — the key move is `Ctrl+↓`.",
   "closing": "That difference is the whole idea: your hands learn the fast way on a real sheet, job by job. || This feed becomes a one-page weekly report — page one of the sale pack, the document the buyers read. You build it in this chapter.",
   "wow": "",
   "convention_line": "The mouse is for reviewing, not building · Name the tabs; outputs left, data right",
   "mac_note": "",
   "story_beat": ""
  },
  "ribbon-by-keyboard": {
   "id": "ribbon-by-keyboard",
   "module": "open-and-set-up",
   "order": "1.1.2",
   "title": "The Ribbon by keyboard",
   "brief": "Every command in Excel is reachable without the mouse: Alt shows a letter on everything. Walk the Ribbon that way once, and turn the gridlines off on Report — it is a page people read, not a grid. The door is `Alt`.",
   "closing": "",
   "wow": "",
   "convention_line": "Borders carry structure, not gridlines · The mouse is for reviewing, not building",
   "mac_note": "",
   "story_beat": ""
  },
  "analyst-setup": {
   "id": "analyst-setup",
   "module": "open-and-set-up",
   "order": "1.1.3",
   "title": "Set Excel up like an analyst",
   "brief": "Before the real work, set the machine up once, the way every desk does on day one. Calculation stays Automatic, iterative calculation goes on, and the four formatting commands you will use all week go on the Quick Access Toolbar. It all lives behind `Alt F T`.",
   "closing": "",
   "wow": "",
   "convention_line": "Set up once: calc mode, iteration, defaults · Alt+number beats a long Alt chord",
   "mac_note": "",
   "story_beat": ""
  },
  "colour-label-hardcode": {
   "id": "colour-label-hardcode",
   "module": "open-and-set-up",
   "order": "1.1.4",
   "title": "Color, label, one hardcode per cell",
   "brief": "The Inputs sheet is where every number someone typed will live, and a reviewer must see at a glance which numbers those are. Color the typed inputs blue, state the units once, and dig the wholesale price out of the formula it is buried in. The brush is `Alt H F C`.",
   "closing": "",
   "wow": "",
   "convention_line": "Inputs blue, formulas black · One input, one cell; formulas reference it · Label the source (\"per utility contract\") · Inputs, calcs, outputs — in that order · A units line: \"USD unless stated\"",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-inherited-file": {
   "id": "challenge-inherited-file",
   "module": "open-and-set-up",
   "order": "1.1.C",
   "title": "Challenge: another cluster’s file",
   "brief": "A sister cluster’s workbook just arrived in the same state: set it up to house standard.",
   "closing": "",
   "wow": "",
   "convention_line": "",
   "mac_note": "",
   "story_beat": ""
  },
  "jump-dont-scroll": {
   "id": "jump-dont-scroll",
   "module": "move-and-select",
   "order": "1.2.1",
   "title": "Jump, don’t scroll",
   "brief": "The associate has five questions about the feed, and every answer is a cell. Analysts do not scroll to a cell — they jump, and the jump key is `Ctrl+↓`.",
   "closing": "",
   "wow": "",
   "convention_line": "The mouse is for reviewing, not building",
   "mac_note": "",
   "story_beat": ""
  },
  "select-like-you-mean-it": {
   "id": "select-like-you-mean-it",
   "module": "move-and-select",
   "order": "1.2.2",
   "title": "Select like you mean it",
   "brief": "Everything you format later starts with the right selection, made in one or two presses. Practice the set on the feed — the workhorse is `Ctrl+Shift+↓`.",
   "closing": "",
   "wow": "",
   "convention_line": "The mouse is for reviewing, not building",
   "mac_note": "",
   "story_beat": ""
  },
  "around-the-workbook": {
   "id": "around-the-workbook",
   "module": "move-and-select",
   "order": "1.2.3",
   "title": "Around the workbook",
   "brief": "Four sheets, one question at a time, and some answers live a sheet away. For a far-off or cross-sheet target you name the cell and go — that is the one honest use of `Ctrl+G`.",
   "closing": "",
   "wow": "",
   "convention_line": "The mouse is for reviewing, not building",
   "mac_note": "",
   "story_beat": ""
  },
  "typed-vs-calculated": {
   "id": "typed-vs-calculated",
   "module": "move-and-select",
   "order": "1.2.4",
   "title": "What’s typed and what’s calculated",
   "brief": "A buyer will ask which cost figures were typed and which are calculated, and the Costs sheet does not say. Make it say: constants blue in one stroke, formulas checked, blanks found — all through `Alt H F D S`.",
   "closing": "",
   "wow": "",
   "convention_line": "Go To Special, show formulas, trace · Inputs blue, formulas black",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-find-and-mark": {
   "id": "challenge-find-and-mark",
   "module": "move-and-select",
   "order": "1.2.C",
   "title": "Challenge: find and mark",
   "brief": "A fresh feed, Revenue now computed — with stray typed numbers hiding in it: find them and mark them blue.",
   "closing": "",
   "wow": "",
   "convention_line": "",
   "mac_note": "",
   "story_beat": ""
  },
  "enter-the-missing-day": {
   "id": "enter-the-missing-day",
   "module": "enter-edit-copy-fill",
   "order": "1.3.1",
   "title": "Enter the missing day",
   "brief": "Airport’s Saturday never came through on the platform feed, and management has emailed the four figures. Enter the day, put 0 into the five blank energy costs in one press, and clear a stray note — the site totals answer the moment the day lands. A row of figures goes in without touching the arrow keys: the key is `Tab`.",
   "closing": "The emailed day is on the feed, and the Airport total moved the moment it landed. Read what Excel tells you (F5): Go To Special lights up the five blanks before you commit, and a total that answers says the entry is in.",
   "wow": "",
   "convention_line": "The count, the proposal, the error code",
   "mac_note": "",
   "story_beat": ""
  },
  "fix-it-in-place": {
   "id": "fix-it-in-place",
   "module": "enter-edit-copy-fill",
   "order": "1.3.2",
   "title": "Fix it in place",
   "brief": "The feed is complete but not clean: two site names are misspelled, one kWh figure was typed as text, and E41 shows 81500 for a single day's revenue. Find each cell, open it and change only what is wrong — a reviewer trusts the person who reads a cell before retyping it. The key is `F2`.",
   "closing": "Every fix went in place: F2 opened the cell, the insertion point moved, only the wrong characters changed — and the site totals beside the feed answered without being asked. || Read what Excel shows you: a figure on the left is text, and a revenue far above its neighbors is a typo, not a record day.",
   "wow": "",
   "convention_line": "Build references by pointing; F2 to read back · The count, the proposal, the error code",
   "mac_note": "",
   "story_beat": ""
  },
  "copy-cut-paste-fill": {
   "id": "copy-cut-paste-fill",
   "module": "enter-edit-copy-fill",
   "order": "1.3.3",
   "title": "Copy, cut, paste, fill",
   "brief": "Report is still blank and the associate wants its skeleton before the figures arrive: title, units, headers, the site list and the week label, plus the feed’s Notes block moved beside the feed. Nothing is typed twice — the headers already sit on Raw, the sites on Inputs, and one label fills five rows and six columns. The key is `Ctrl+C`.",
   "closing": "The Report has its shape, and nothing on it was typed twice: the headers came from Raw, the sites from Inputs, and one week label went down five rows and across six columns from a single copy — fill, don’t retype (E3). || The Notes block now sits beside the feed where a reader finds it, and the feed’s block ends where the data ends.",
   "wow": "",
   "convention_line": "Ctrl+D down, Ctrl+R across · Inputs, calcs, outputs — in that order",
   "mac_note": "",
   "story_beat": ""
  },
  "paste-special-values": {
   "id": "paste-special-values",
   "module": "enter-edit-copy-fill",
   "order": "1.3.4",
   "title": "Paste Special: values, formats, transpose",
   "brief": "The Report needs this week’s site totals and last week’s revenue beside them — as numbers that stay put once the page is sent, not links that move with the feed. Paste Special brings one aspect of what you copied: values only, formats only, or a block turned on its side, so the snapshot is taken on purpose. The key is `Ctrl+Alt+V`.",
   "closing": "The Report now carries this week’s and last week’s site figures as a snapshot: the feed can move, the page will not — Paste Special on purpose (E4). || The total row went in plain, and its SUM followed the paste to C5:C9; the site list stands across the sensitivity table without a name retyped.",
   "wow": "",
   "convention_line": "Values to snapshot, never over live formulas",
   "mac_note": "",
   "story_beat": ""
  },
  "find-replace-timeline": {
   "id": "find-replace-timeline",
   "module": "enter-edit-copy-fill",
   "order": "1.3.5",
   "title": "Find, replace, fill a timeline",
   "brief": "Last week’s label, w/c 08 Sep (week commencing), still sits in twelve cells across the Report and Inputs, one Airport row on the feed is spelled Airprot, and the daily table has no day header. Replace the label on the Report and on Inputs, reading the count each time, find and fix the typo, then let Fill Series write Mon–Sat and the dates. The key is `Ctrl+H`.",
   "closing": "The stale week label is gone from both sheets in two Replace Alls, and Excel reported how many cells it touched each time — read what it tells you (F5). || The daily table now carries one timeline row: Mon to Sat with the dates under them, written as a series rather than typed six times (C2).",
   "wow": "",
   "convention_line": "The count, the proposal, the error code · Timeline on top, equal widths",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-complete-the-feed": {
   "id": "challenge-complete-the-feed",
   "module": "enter-edit-copy-fill",
   "order": "1.3.C",
   "title": "Challenge: complete the feed",
   "brief": "A fresh cut of the Austin feed came in with a day missing, a text figure and typos: complete it, clean it, then start the Summary tab with a snapshot and the week’s timeline.",
   "closing": "",
   "wow": "",
   "convention_line": "Values to snapshot, never over live formulas",
   "mac_note": "",
   "story_beat": ""
  },
  "rows-cols-honest-totals": {
   "id": "rows-cols-honest-totals",
   "module": "structure",
   "order": "1.4.1",
   "title": "Rows and columns that keep the totals honest",
   "brief": "Cedar Park opened this week and needs a row inside the Report block, the old platform’s Old code column has to go, and a Margin % column is coming. Insert and delete whole rows and columns and watch the total row follow every edit — then see what happens to a SUM when the column it reads is deleted. The key is `Ctrl+Shift+=`.",
   "closing": "Cedar Park’s row went in inside the block, the Old code column came out and Margin % went in, and the total row followed every edit without a formula retyped — a total that follows its rows is the first check (F1). || Deleting the column a SUM reads turned it to #REF!: that is a message, not damage — read it (F5) — and Ctrl+Z put the feed and its totals back.",
   "wow": "",
   "convention_line": "The check is a live difference → 0 · Write once, fill right · The count, the proposal, the error code",
   "mac_note": "",
   "story_beat": ""
  },
  "widths-heights-autofit": {
   "id": "widths-heights-autofit",
   "module": "structure",
   "order": "1.4.2",
   "title": "Widths, heights, AutoFit",
   "brief": "The Report’s columns are still Excel’s defaults: South Lamar is cut off at the default width, the header row is clipped, and every column sits at 8.43 characters wide. Set the day columns to one width and the comparison columns to another, fit the label column to its site names, size the title row, and wrap the headers so nothing is clipped. The key is `Alt H O W`.",
   "closing": "The Report’s columns now read as a page: the six day columns share one width, the comparison columns another, the label column fits its longest site name, and nothing in the header row is clipped — equal period columns (C2). || AutoFit fits whatever happens to sit in a column — one stray label lower down in E breaks the equal period columns — so set period columns by hand, and let AutoFit size the labels and the wrapped rows.",
   "wow": "",
   "convention_line": "Timeline on top, equal widths",
   "mac_note": "",
   "story_beat": ""
  },
  "hide-group-freeze": {
   "id": "hide-group-freeze",
   "module": "structure",
   "order": "1.4.3",
   "title": "Hide, group, freeze",
   "brief": "The Report’s Energy cost and Gross profit columns are workings the reader does not need, and a buyer’s analyst who finds a hidden column will wonder what else is hidden. Hide them the way most people do, then unhide them and group them instead, and freeze the heads so the page scrolls without losing them. The key is `Alt+Shift+→`.",
   "closing": "The two working columns are grouped, not hidden: a hidden column vanishes and gets forgotten, a grouped one shows its button and folds away when the reader wants the page clean (C7). || The title, units, header row and site labels are frozen at B5, so the Report scrolls without losing its heads (C8) — and Cedar Park’s kWh still moves the Total.",
   "wow": "",
   "convention_line": "Hidden columns get forgotten · Keep the timeline and labels in view",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-reshape-the-report": {
   "id": "challenge-reshape-the-report",
   "module": "structure",
   "order": "1.4.C",
   "title": "Challenge: reshape the report",
   "brief": "A sister cluster’s KPI report arrived with a site missing, a stale column, uneven widths, a hidden column and nothing frozen: reshape it to house standard, and the totals must still tie.",
   "closing": "",
   "wow": "",
   "convention_line": "The check is a live difference → 0 · Timeline on top, equal widths · Hidden columns get forgotten · Keep the timeline and labels in view",
   "mac_note": "",
   "story_beat": ""
  },
  "numbers-a-banker-can-read": {
   "id": "numbers-a-banker-can-read",
   "module": "format",
   "order": "1.5.1",
   "title": "Numbers a banker can read",
   "brief": "Thousands separators, no decimals, negatives in parentheses for the figures; one decimal for Margin %; three for the energy price; a percentage for the target margin; currency on the total row. Do it with Ctrl+1 first, then with the shortcuts.",
   "closing": "",
   "wow": "Every line reads the same way down the page. A negative shows in parentheses, so nobody mistakes it for a dash.",
   "convention_line": "Parentheses, never a leading minus · One decimals setting per line",
   "mac_note": "",
   "story_beat": ""
  },
  "fonts-fills-borders": {
   "id": "fonts-fills-borders",
   "module": "format",
   "order": "1.5.2",
   "title": "Fonts, fills, borders",
   "brief": "Bold the title and totals and give the totals a top border, not a grid. Fill the input block a light tint, color the two typed rates blue, and size the title one step up.",
   "closing": "",
   "wow": "A reviewer can now tell an input from a formula and a total from a line item without reading a single number.",
   "convention_line": "A top border, never an all-borders grid · A tint marks the input block · No color for decoration",
   "mac_note": "",
   "story_beat": ""
  },
  "alignment-and-titles": {
   "id": "alignment-and-titles",
   "module": "format",
   "order": "1.5.3",
   "title": "Alignment and titles",
   "brief": "Center the title across the report with Center Across Selection, never merge. Right-align the headers over the numbers, indent the day lines under each site, and wrap the long note.",
   "closing": "",
   "wow": "Insert a column through the title: it still sits centered, because nothing was merged.",
   "convention_line": "Merged cells break everything · Indent sub-items; headers over numbers",
   "mac_note": "",
   "story_beat": ""
  },
  "the-style-pass": {
   "id": "the-style-pass",
   "module": "format",
   "order": "1.5.4",
   "title": "The style pass",
   "brief": "A second, unformatted block arrives: the Costs summary. Bring it to the same standard in one pass with F4 to repeat the last format, the number shortcuts and the Quick Access Toolbar, then remove a stray all-borders grid.",
   "closing": "",
   "wow": "Two blocks, one look, in under a minute: formatting is a pass you make, not a job you do cell by cell.",
   "convention_line": "A top border, never an all-borders grid · Parentheses, never a leading minus · One decimals setting per line",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-to-standard-in-three-minutes": {
   "id": "challenge-to-standard-in-three-minutes",
   "module": "format",
   "order": "1.5.C",
   "title": "Challenge: to standard in three minutes",
   "brief": "A seeded, unformatted weekly report for another cluster: figures, percentages, a title, totals and an input block. Bring it to the standard.",
   "closing": "",
   "wow": "",
   "convention_line": "Parentheses, never a leading minus · One decimals setting per line · A top border, never an all-borders grid · Merged cells break everything · Inputs blue, formulas black",
   "mac_note": "",
   "story_beat": ""
  },
  "point-dont-type": {
   "id": "point-dont-type",
   "module": "formulas",
   "order": "1.6.1",
   "title": "Point, don’t type",
   "brief": "Build gross profit, gross margin % and average price per kWh for one site by pointing at the cells with the arrow keys, never typing an address. Read each formula back with F2.",
   "closing": "",
   "wow": "Change the site’s revenue on Raw and watch all three lines move. You built them by pointing, so they point back.",
   "convention_line": "Build references by pointing; F2 to read back",
   "mac_note": "",
   "story_beat": ""
  },
  "sum-family-and-autosum": {
   "id": "sum-family-and-autosum",
   "module": "formulas",
   "order": "1.6.2",
   "title": "SUM family and AutoSum",
   "brief": "Total the six sites with Alt+= in one press across the block. Then AVERAGE, MIN, MAX, COUNT and COUNTA for the week summary, and see what a blank does to AVERAGE.",
   "closing": "",
   "wow": "Six totals from one press, and the summary line tells you a blank is not a zero.",
   "convention_line": "Alt+= once, across the block",
   "mac_note": "",
   "story_beat": ""
  },
  "anchors-dollar-and-f4": {
   "id": "anchors-dollar-and-f4",
   "module": "formulas",
   "order": "1.6.3",
   "title": "Anchors: $ and F4",
   "brief": "The wholesale energy price and target margin live on Inputs. Write one energy-cost line that fills down without breaking, cycle F4 through the four anchor states, and fix a mixed-anchor table of sites by price scenario.",
   "closing": "",
   "wow": "One input cell, referenced thirty times. Change it once and the whole table follows.",
   "convention_line": "Know the four anchor states · One input, one cell; formulas reference it",
   "mac_note": "",
   "story_beat": ""
  },
  "link-across-sheets": {
   "id": "link-across-sheets",
   "module": "formulas",
   "order": "1.6.4",
   "title": "Link across sheets",
   "brief": "Replace the typed site figures on Report with live links to Raw and Costs, fill them down, and color the links green. External-workbook links would be red, and are avoided.",
   "closing": "",
   "wow": "The Report is fully live: correct a figure in the feed and page one updates without anyone retyping.",
   "convention_line": "Links green; external links avoided · Check for stray links before sending",
   "mac_note": "",
   "story_beat": ""
  },
  "one-formula-per-row-filled-right": {
   "id": "one-formula-per-row-filled-right",
   "module": "formulas",
   "order": "1.6.5",
   "title": "One formula per row, filled right",
   "brief": "Build this week’s six-day block. Write each line once in the Monday column, select across the week with Ctrl+Shift+→ and fill with Ctrl+R; fix a row whose Thursday was retyped; show the formulas with Ctrl+` to see the pattern.",
   "closing": "",
   "wow": "Show formulas: every row is one formula, repeated. That pattern is what a reviewer checks first.",
   "convention_line": "Write once, fill right · Ctrl+D down, Ctrl+R across",
   "mac_note": "",
   "story_beat": ""
  },
  "read-the-error-follow-the-trail": {
   "id": "read-the-error-follow-the-trail",
   "module": "formulas",
   "order": "1.6.6",
   "title": "Read the error, follow the trail",
   "brief": "Five planted errors sit on Costs: #REF!, #DIV/0!, #NAME?, #VALUE! and #N/A. Read each code, trace it with Ctrl+[ and Ctrl+], and fix the input or the formula. Never paste a value over it.",
   "closing": "",
   "wow": "Five errors, five causes, five fixes upstream. Costs is clean and nothing was hardcoded to make it so.",
   "convention_line": "The count, the proposal, the error code · Go To Special, show formulas, trace",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-the-site-pnl": {
   "id": "challenge-the-site-pnl",
   "module": "formulas",
   "order": "1.6.C",
   "title": "Challenge: the site P&L",
   "brief": "A seeded site block with typed figures, an Inputs sheet, two errors and one hardcoded rate: link it, total it, anchor it, fix it, fill the week right.",
   "closing": "",
   "wow": "",
   "convention_line": "Links green; external links avoided · Inputs blue, formulas black · Write once, fill right · One input, one cell; formulas reference it",
   "mac_note": "",
   "story_beat": ""
  },
  "fit-to-one-page": {
   "id": "fit-to-one-page",
   "module": "present-and-audit",
   "order": "1.7.1",
   "title": "Fit to one page",
   "brief": "Set the Report up to print: landscape, fit to one page wide, rows 1 to 3 as print titles, a footer with the file name and date, gridlines off in print. Then read the page the way the MD will.",
   "closing": "",
   "wow": "Print preview shows one page, titled, dated and footed. The report is a document now, not a sheet.",
   "convention_line": "Fit to page, titles, footer · Title, units, timeline, then the answer · Never overwrite the only copy",
   "mac_note": "",
   "story_beat": ""
  },
  "the-checks-row": {
   "id": "the-checks-row",
   "module": "present-and-audit",
   "order": "1.7.2",
   "title": "The checks row",
   "brief": "Add a Checks block under the report: report revenue less Raw revenue, sites sum less grand total, margin between 0 and 100%. Label each check, and freeze the block in view.",
   "closing": "",
   "wow": "Three checks, three zeros. Break a link on purpose and one of them turns non-zero: the page tells you before a buyer does.",
   "convention_line": "The check is a live difference → 0",
   "mac_note": "",
   "story_beat": ""
  },
  "hardcode-hunt": {
   "id": "hardcode-hunt",
   "module": "present-and-audit",
   "order": "1.7.3",
   "title": "Hardcode hunt",
   "brief": "The associate marked up a version of Report with eight planted faults from the day-one list: a literal in a formula, a black input, a retyped Thursday, a title centered with spaces, a minus sign, missing units, an all-borders grid, a hidden column. Find each with Go To Special, show formulas and tracing; fix every one and change nothing else.",
   "closing": "",
   "wow": "Eight faults found, eight fixed, nothing else touched. That is the audit pass you make before anything leaves your desk.",
   "convention_line": "Go To Special, show formulas, trace",
   "mac_note": "",
   "story_beat": ""
  },
  "challenge-audit-before-you-send": {
   "id": "challenge-audit-before-you-send",
   "module": "present-and-audit",
   "order": "1.7.C",
   "title": "Challenge: audit before you send",
   "brief": "A seeded report with five planted faults from the list: find and fix all five in three minutes, then set landscape and fit to page.",
   "closing": "",
   "wow": "",
   "convention_line": "Go To Special, show formulas, trace · Fit to page, titles, footer",
   "mac_note": "",
   "story_beat": ""
  },
  "project-the-weekly-kpi-report": {
   "id": "project-the-weekly-kpi-report",
   "module": "project-and-assessment",
   "order": "1.8.P",
   "title": "Project: the weekly KPI report",
   "brief": "Management’s next feed has arrived and the Report is blank. Build the linked, totaled, margin-bearing, formatted, checked, print-ready one-page report the chapter has been building. This is page one of the Project Volt pack.",
   "closing": "",
   "wow": "Page one of the data room, built by you from a raw feed, and every number on it ties.",
   "convention_line": "Inputs blue, formulas black · Links green; external links avoided · One input, one cell; formulas reference it · A units line: \"USD unless stated\" · Parentheses, never a leading minus · One decimals setting per line · A top border, never an all-borders grid · Merged cells break everything · The check is a live difference → 0 · Fit to page, titles, footer",
   "mac_note": "",
   "story_beat": ""
  },
  "assessment-monday-morning": {
   "id": "assessment-monday-morning",
   "module": "project-and-assessment",
   "order": "1.8.A",
   "title": "Assessment: Monday morning",
   "brief": "Same brief, fresh figures, one extra site. Eight minutes on the clock from your first key, solo and keyboard-only, for the Verified certificate.",
   "closing": "",
   "wow": "",
   "convention_line": "Inputs blue, formulas black · Links green; external links avoided · One input, one cell; formulas reference it · A units line: \"USD unless stated\" · Parentheses, never a leading minus · One decimals setting per line · A top border, never an all-borders grid · Merged cells break everything · The check is a live difference → 0 · Fit to page, titles, footer",
   "mac_note": "",
   "story_beat": ""
  },
  "test-out-of-foundations": {
   "id": "test-out-of-foundations",
   "module": "project-and-assessment",
   "order": "1.8.T",
   "title": "Test out of Foundations",
   "brief": "Ten tasks across the seven modules on one seeded workbook, five minutes. Pass, and the chapter is skipped.",
   "closing": "",
   "wow": "",
   "convention_line": "",
   "mac_note": "",
   "story_beat": ""
  }
 },
 "goals": {
  "inherited-workbook": [
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "0",
    "text": "Round one, the slow way: walk down the dates with ↓ until you reach the last one, A61.",
    "teach": "The arrow keys move the active cell one cell per press — feel how long sixty rows takes.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "1",
    "text": "Round two: back to the top with Ctrl+Home, then the same trip in one Ctrl+↓ — the Name Box reads A61.",
    "teach": "Ctrl+Home returns to A1 and Ctrl+Arrow jumps to the edge of the data in one press; the Name Box, left of the formula bar, shows the cell you landed on.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "2",
    "text": "Take the two dates above with Shift+↑, then the whole date column in one Ctrl+Shift+↑: the selection reads A1:A61.",
    "teach": "Shift+Arrow grows a selection one cell per press; add Ctrl and the same jump selects to the edge in one press.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "3",
    "text": "Walk the tabs to Costs and land on the Domain total E4: the grid shows a number, the formula bar shows =B4+C4+D4.",
    "teach": "A workbook is the file and the tabs along the bottom are its sheets: Ctrl+PgDn / Ctrl+PgUp walk them, and the formula bar shows what the active cell really holds.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "4",
    "text": "Sheet2 is the associate’s inputs scratch — go there and rename it Inputs.",
    "teach": "Rename Sheet, Home › Format (Alt, H, O, R), opens the active tab’s name: type the new one and press Enter.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "5",
    "text": "Old wk37 is a dead half-export — delete it and confirm.",
    "teach": "Delete Sheet (Alt, H, D, S) removes the active sheet; Excel asks first, because a deleted sheet cannot be undone.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "6",
    "text": "Insert the sheet the weekly report will live on and rename it Report.",
    "teach": "Shift+F11 inserts a new worksheet in front of the active one and makes it active.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "inherited-workbook",
    "goal_index": "7",
    "text": "The report reads first: move Report to the front of the workbook.",
    "teach": "Move or Copy Sheet (Alt, H, O, M) moves the active sheet: ↑ ↓ pick where it will sit, Enter confirms.",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "ribbon-by-keyboard": [
   {
    "lesson_id": "ribbon-by-keyboard",
    "goal_index": "0",
    "text": "Open the Ribbon with Alt, step into Home › Font, then back all the way out with Esc.",
    "teach": "Alt shows KeyTips: every tab and command has a letter, and Esc backs out one level at a time.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "ribbon-by-keyboard",
    "goal_index": "1",
    "text": "Walk to the View tab with Alt, W, look at what lives there, and leave with Esc.",
    "teach": "The tab letters never change: H Home, N Insert, P Page Layout, M Formulas, A Data, W View.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "ribbon-by-keyboard",
    "goal_index": "2",
    "text": "Report is a page someone reads: turn its gridlines off.",
    "teach": "View › Show › Gridlines (Alt, W, V, G) toggles the grid on the active sheet only.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "ribbon-by-keyboard",
    "goal_index": "3",
    "text": "Open Format Cells with Ctrl+1, glance at its tabs, and close it with Esc.",
    "teach": "Ctrl+1 opens Format Cells from anywhere — the dialog behind most formatting.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "ribbon-by-keyboard",
    "goal_index": "4",
    "text": "Open the same dialog the long way, Alt, H, O, E, and close it again.",
    "teach": "Every dialog also has a Ribbon route — Format Cells is Home › Format › Format Cells, Alt, H, O, E.",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "analyst-setup": [
   {
    "lesson_id": "analyst-setup",
    "goal_index": "0",
    "text": "Press F9 once — on Automatic it is instant, and your hands should know it.",
    "teach": "Calculation is Automatic here; F9, Calculate Now, is the key you live on when a big model goes Manual.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "analyst-setup",
    "goal_index": "1",
    "text": "Open Excel Options and enable iterative calculation.",
    "teach": "Alt, F, T opens Excel Options; on the Formulas page, I enables iterative calculation, which circular models need.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "analyst-setup",
    "goal_index": "2",
    "text": "Add Font Color to the Quick Access Toolbar.",
    "teach": "Q opens the Quick Access Toolbar page: ↑ ↓ pick a command, A adds it, Enter is OK.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "analyst-setup",
    "goal_index": "3",
    "text": "Add Fill Color the same way.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "analyst-setup",
    "goal_index": "4",
    "text": "Add Borders.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "analyst-setup",
    "goal_index": "5",
    "text": "Add Decrease Decimal, the last of the four.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "analyst-setup",
    "goal_index": "6",
    "text": "Run one from the keyboard: Alt, then 2 — Undo, straight off the toolbar.",
    "teach": "Alt alone numbers the toolbar 1–9; Alt then the number runs that command from anywhere.",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "colour-label-hardcode": [
   {
    "lesson_id": "colour-label-hardcode",
    "goal_index": "0",
    "text": "The inputs scratch needs an owner’s pass: move to the Inputs sheet.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "colour-label-hardcode",
    "goal_index": "1",
    "text": "Add the units line: type USD unless stated into A2.",
    "teach": "Type and press Enter to commit; every pack page states its currency once, near the top.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "colour-label-hardcode",
    "goal_index": "2",
    "text": "Color the typed figures blue — the margin target B5 and the kWh estimate B6.",
    "teach": "House rule: anything typed is blue, anything calculated stays black, so a reviewer sees the drivers at a glance.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "colour-label-hardcode",
    "goal_index": "3",
    "text": "The wholesale price deserves its own cell: type 0.13 into B4 and color it blue too.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "colour-label-hardcode",
    "goal_index": "4",
    "text": "Label where the number comes from: per utility contract in C4.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "colour-label-hardcode",
    "goal_index": "5",
    "text": "B14 still hides the price in =B6*0.13: rewrite it as =B6*B4, so the price lives in one place.",
    "teach": "F2 opens the cell for editing with the caret at the end — read a formula before you change it.",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "challenge-inherited-file": [
   {
    "lesson_id": "challenge-inherited-file",
    "goal_index": "0",
    "text": "Rename Sheet2 to Inputs, delete Old wk37, and get a Report sheet in front.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-inherited-file",
    "goal_index": "1",
    "text": "Gridlines off on Report — someone reads this page.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-inherited-file",
    "goal_index": "2",
    "text": "State the units on Inputs: USD unless stated in A2.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-inherited-file",
    "goal_index": "3",
    "text": "Color the typed inputs B5 and B6 blue.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-inherited-file",
    "goal_index": "4",
    "text": "Put the wholesale price in B4 blue, label C4 per utility contract, and point the bill formula B14 at B4.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "jump-dont-scroll": [
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "0",
    "text": "The questions are about the feed: move to Raw.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "1",
    "text": "“How many days came through?” — jump to the last date with Ctrl+↓.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "2",
    "text": "“Which columns does it carry?” — back to the top, then along the headers to F1.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "3",
    "text": "“Is every energy cost in?” — ride Ctrl+↓ down column F; it stops at F11, right above the first missing figure.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "4",
    "text": "“Anything below the feed?” — Ctrl+End to the far corner, Home, then up to the Notes header in A64.",
    "teach": "Ctrl+End jumps to the sheet’s last used cell, and Home snaps to column A of the row you are on.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "5",
    "text": "Skim the feed a screen at a time: one PgUp, one PgDn.",
    "teach": "PgDn and PgUp move a screen at a time — for reading through, not for reaching a cell.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "jump-dont-scroll",
    "goal_index": "6",
    "text": "Back to the top for the next job: Ctrl+Home.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "select-like-you-mean-it": [
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "0",
    "text": "Move to Raw, where the selecting is.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "1",
    "text": "Select Revenue from its header to the last figure: E1, then one Ctrl+Shift+↓.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "2",
    "text": "Collapse to A1, then select the whole header row with Shift+Space.",
    "teach": "Shift+Space selects the active row; Ctrl+Space selects the active column.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "3",
    "text": "Now the whole of column E with Ctrl+Space.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "4",
    "text": "Select the whole feed in one press: Ctrl+A.",
    "teach": "Ctrl+A selects the current region — the block of data around the active cell.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "5",
    "text": "Press Ctrl+A a second time: the entire sheet.",
    "teach": "Ctrl+A pressed again widens to the entire sheet.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "select-like-you-mean-it",
    "goal_index": "6",
    "text": "Collapse to A1 with Ctrl+Home, then take everything used — feed, notes and the totals block — with Ctrl+Shift+End.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "around-the-workbook": [
   {
    "lesson_id": "around-the-workbook",
    "goal_index": "0",
    "text": "Warm up the tab keys: Ctrl+PgDn to Costs at the end, Ctrl+PgUp back to Report.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "around-the-workbook",
    "goal_index": "1",
    "text": "Management asks about the Airport Saturday: land on Raw!F61 in one jump.",
    "teach": "Ctrl+G (or F5) jumps to anything you can name — its job is far-off or cross-sheet targets, never the next cell over.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "around-the-workbook",
    "goal_index": "2",
    "text": "Select the whole Costs table by address: Costs!A3:E8.",
    "teach": "A sheet-qualified reference — Costs!A3:E8 — names the sheet, an exclamation mark, then the cell or range.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "around-the-workbook",
    "goal_index": "3",
    "text": "Hop home to Report on the tab keys, then land straight back on Costs!B7 in one jump.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "around-the-workbook",
    "goal_index": "4",
    "text": "Finish on the report page: Report!A1, one jump.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "typed-vs-calculated": [
   {
    "lesson_id": "typed-vs-calculated",
    "goal_index": "0",
    "text": "The question is about Costs: go there.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "typed-vs-calculated",
    "goal_index": "1",
    "text": "Select the table body B4:E8, edge to edge.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "typed-vs-calculated",
    "goal_index": "2",
    "text": "Pick out the constants — everything someone typed — and color them blue in one stroke.",
    "teach": "Go To Special (Alt, H, F, D, S) selects by kind inside your selection — O is Constants, F Formulas, Enter Blanks.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "typed-vs-calculated",
    "goal_index": "3",
    "text": "Select the body again and pick out the formulas — only the Domain total E4 lights up, and it stays black.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "typed-vs-calculated",
    "goal_index": "4",
    "text": "One more pass: the blanks — the two sites with no maintenance figure.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "challenge-find-and-mark": [
   {
    "lesson_id": "challenge-find-and-mark",
    "goal_index": "0",
    "text": "Land on the feed’s last date in one jump from the top of Raw.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-find-and-mark",
    "goal_index": "1",
    "text": "Back to the top, then along the headers to the last column, F1.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-find-and-mark",
    "goal_index": "2",
    "text": "Select everything used on the sheet from A1 in one stroke.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-find-and-mark",
    "goal_index": "3",
    "text": "Select the Revenue figures E2:E60, edge to edge.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-find-and-mark",
    "goal_index": "4",
    "text": "Go To Special, Constants — then color every typed number in the block blue.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "enter-the-missing-day": [
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "0",
    "text": "Airport’s Saturday never came through: jump to the first blank cell of its row, Raw!C61.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "1",
    "text": "Management emailed the day: enter 2,500 kWh in C61 and the price $0.48 in D61, moving right with Tab.",
    "teach": "Tab commits the entry and steps one cell right, and Excel remembers where the run began — that is where Enter will return you.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "2",
    "text": "Finish the row with the revenue $1,200.00 in E61 and the energy cost $325.00 in F61, then Enter to land in C62.",
    "teach": "Enter after a Tab run commits and drops to the column the run started in, one row down — where the next record begins.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "3",
    "text": "Start retyping the site name over B61, then look again — Airport is right, so discard the entry and keep it.",
    "teach": "Esc throws away an entry you have started: the cell keeps what it had, and nothing is committed.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "4",
    "text": "Five Energy cost cells in column F are blank: select the feed from the top, pick out the blanks with Go To Special and count them.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "5",
    "text": "Type 0 once and commit it into all five blank cells of the Energy cost column at the same time.",
    "teach": "Ctrl+Enter commits one entry into every selected cell at once — five blanks, one press.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "6",
    "text": "A stray “draft” note sits in H3, above the site totals block: clear it.",
    "teach": "Delete clears what the cell holds and leaves its formatting behind — the italic stays for whatever is typed there next.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "enter-the-missing-day",
    "goal_index": "7",
    "text": "Does it tie? Watch Airport’s Saturday kWh in C61 change to 3,000 and the Airport line of the site totals, I12, answer.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "fix-it-in-place": [
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "0",
    "text": "Mueller is misspelled somewhere in the 60-row feed: move to Raw and find Muller.",
    "teach": "Ctrl+F opens Find: type part of what you want, Enter jumps to the next cell containing it, Esc closes the card.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "1",
    "text": "Open B14 with F2, move the insertion point to just after Mu, and insert the e so it reads Mueller.",
    "teach": "In Edit mode, Home and End send the insertion point to either end of the entry and ← → step it one character; typing inserts there.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "2",
    "text": "Riverside lost its e in one row: find Riversid, Find Next past the first hit (a correct Riverside), and add the e.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "3",
    "text": "C33 shows 1,240 on the left — text with a trailing space: find it, open it, delete the space and commit it as a number.",
    "teach": "A figure sitting on the left is text, not a number; Backspace deletes the character before the insertion point, so the trailing space goes and 1,240 snaps right.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "4",
    "text": "E41 reads 81500 for one day of South Lamar revenue when kWh × price says 1075: find it and type 1075 over it.",
    "teach": "Typing on a cell replaces its whole contents — no F2 when nothing in the old entry is worth keeping.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "5",
    "text": "The associate asks what was there before: Ctrl+Z, and E41 shows 81500 again.",
    "teach": "Ctrl+Z undoes the last change and Ctrl+Y puts it back, so a fix can be tried, read and kept.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "6",
    "text": "The figure was wrong after all: Ctrl+Y puts 1075 back in E41.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "fix-it-in-place",
    "goal_index": "7",
    "text": "Does it tie? Watch C33, a Riverside kWh figure, change to 2,000 and Riverside’s kWh total in I10 answer.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "copy-cut-paste-fill": [
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "0",
    "text": "Title the page: “Voltline - Austin Weekly KPI Report, w/c 15 Sep 2026” in A1, “USD unless stated” in A2, then Site and Week in A4:B4.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "1",
    "text": "The feed’s totals block already carries the figure headers: copy Raw!I7:K7 and paste them onto C4:E4, then drop the marquee.",
    "teach": "Ctrl+C copies and Ctrl+X cuts the selection; Ctrl+V pastes it at the cursor, formats included; Esc drops the marquee, the moving border around what you copied.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "2",
    "text": "The site list lives on Inputs: copy Inputs!A9:A13 and drop it under Site at A5 with Enter.",
    "teach": "After a copy, Enter pastes once and drops the marquee in the same press — the paste for a single destination.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "3",
    "text": "Copy the reporting week from Inputs!B3 onto B5, then fill it down the five site rows B5:B9 with Ctrl+D.",
    "teach": "Ctrl+D fills the selection from its top row and Ctrl+R from its left column — one entry, filled, never retyped.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "4",
    "text": "Label the daily block below the table: kWh sold by day in A12, then Week, Day and Date in A13:A15.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "5",
    "text": "The daily block needs the same five sites: copy A5:A9 and drop them at A16 with Enter.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "6",
    "text": "The daily block’s Week row takes the same label: copy it from B9 to B13, then fill it right across B13:G13 with Ctrl+R.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "7",
    "text": "The Notes block sits under the feed where nobody reads it: cut Raw!A64:A67 and paste it beside the feed at H1.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "copy-cut-paste-fill",
    "goal_index": "8",
    "text": "Does it tie? Watch Domain’s Monday kWh in Raw!C8 change to 3,000 and Domain’s kWh total in I8 answer.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "paste-special-values": [
   {
    "lesson_id": "paste-special-values",
    "goal_index": "0",
    "text": "Two more figure columns are coming: type Gross profit ($) in F4 and Avg price ($/kWh) in G4 as one Tab run.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "1",
    "text": "The associate wants last week beside this week: copy Raw’s Prior week rev and Old code block L7:M12 and paste values only onto H4.",
    "teach": "Paste Special, Ctrl+Alt+V, pastes one aspect of the copy — V values only, T formats only, E transposed — then Enter confirms.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "2",
    "text": "Four new headers, one style: copy the kWh sold header C4 and paste its format only onto F4:I4 with Paste Formats.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "3",
    "text": "Snapshot this week: copy the five sites’ live totals Raw!I8:K12 and paste values only onto C5, so the page holds numbers, not links.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "4",
    "text": "Type Total in A10, then copy Raw’s total row I13:K13 and paste it plain onto C10: the SUM re-points to C5:C9.",
    "teach": "A pasted formula keeps its shape, not its cells: the references shift with the move, so =SUM(I8:I12) becomes =SUM(C5:C9) — a $ would pin them.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "5",
    "text": "Start the sensitivity block under the daily table: Energy cost sensitivity ($/wk) in A22 and Price per kWh in A23.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "6",
    "text": "The sensitivity table needs the sites across its top: copy A5:A9 and paste them transposed onto B23, one row of five.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "paste-special-values",
    "goal_index": "7",
    "text": "Does it tie? Watch Domain’s Monday kWh in Raw’s C8 change: the live total I8 moves, and the Report’s snapshot C5 stays put.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "find-replace-timeline": [
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "0",
    "text": "Eleven cells on the Report still read w/c 08 Sep: swap every one for w/c 15 Sep with Replace All and read the count — eleven.",
    "teach": "Ctrl+H opens Replace: type what to find, Tab, what to put there, then Alt+A replaces every match on this sheet and reports how many cells changed.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "1",
    "text": "Replace All only touches the active sheet: move to Inputs and replace the stale week label in B3 the same way — the count reads one.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "2",
    "text": "One Airport row on the feed is spelled Airprot: move to Raw and find it with Ctrl+F.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "3",
    "text": "Nothing in Airprot is worth keeping: type Airport over B55.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "4",
    "text": "Back on the Report, the daily table needs its day header: type Mon in B14, select B14:G14 and let Fill Series carry it to Sat.",
    "teach": "Fill Series (Alt, H, F, I, S) continues the pattern your first cells set across the selection: Mon runs to Sat, 15 and 16 run on to 20.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "5",
    "text": "The dates go under the days: type the first two, 15 and 16, into B15 and C15 as a Tab run.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "6",
    "text": "Select B15:G15 and Fill Series carries 15 and 16 on to 20.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "find-replace-timeline",
    "goal_index": "7",
    "text": "Does it tie? Watch Airport’s Monday kWh in Raw’s C56 change to 3,000 and the Airport line of the site totals, I12, answer.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "challenge-complete-the-feed": [
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "0",
    "text": "Airport’s Saturday never came through: enter management’s figures in C61:F61 — 2,500 kWh, $0.48, $1,200.00 revenue and $325.00 energy cost.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "1",
    "text": "Mueller is misspelled Muller in one row of the 60-row feed: find it and fix it in place.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "2",
    "text": "Riverside reads Riverisde in three rows: Replace All of them in one step and read the count.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "3",
    "text": "The kWh figure “1,240” in the Riverside rows was typed as text and sits on the left: make it a number.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "4",
    "text": "Copy the site totals header H7:K7, insert a sheet named Summary in front, drop the header on its A1 and label E1 Snapshot.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "5",
    "text": "With the feed complete, paste Raw’s site rows H8:K12 as values onto Summary!A2: a snapshot is values, never a live formula.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-complete-the-feed",
    "goal_index": "6",
    "text": "Under the snapshot, type Day in A8 and fill a Mon–Sat timeline across B8:G8.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "rows-cols-honest-totals": [
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "0",
    "text": "Cedar Park opened this week: select Airport’s row 9 and insert a blank row above it — the Total in C11 follows to =SUM(C5:C10).",
    "teach": "Ctrl+Shift+= inserts whole rows or columns at the selection, Ctrl+- deletes them, and a SUM whose range straddles the insert grows to take the new row in.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "1",
    "text": "Name the new site: type Cedar Park in A9, then fill the week label down from B8 into B9 with Ctrl+D.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "2",
    "text": "Enter Cedar Park’s week across C9:E9 with Tab: 2,140 kWh, $1,005.80 revenue, $278.20 energy cost — the totals in C11:E11 grow together.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "3",
    "text": "The Old code column is the old platform’s: select column I from its header I4 and delete the whole column in one press.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "4",
    "text": "Margin % belongs before Prior week rev: insert a column at H and type Margin % in H4 — the header comes out bold.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "5",
    "text": "On Raw, delete the Revenue column E and read the site totals block: every Revenue SUM now says #REF! instead of a number.",
    "teach": "#REF! means the formula pointed at a cell that no longer exists: delete a column a SUM reads and it breaks, and Ctrl+Z brings both back.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "6",
    "text": "Read the error, then undo: Ctrl+Z brings the Revenue column back and Domain’s Revenue SUM in J8 reads a number again.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "rows-cols-honest-totals",
    "goal_index": "7",
    "text": "Does it tie? Watch Cedar Park’s kWh in C9 change to 3,000 and the Total in C11 answer.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "widths-heights-autofit": [
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "0",
    "text": "The daily table’s six day columns B:G should share one width: select them from its timeline row and set Column Width 12.",
    "teach": "Column Width (Alt, H, O, W) sets every selected column to one width in Excel character units: select the columns first, then type the number and Enter.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "1",
    "text": "Margin % and Prior week rev ($) in H:I are the comparison columns: select both from the header row and set them to 14.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "2",
    "text": "Fit the label column to its site names, not the title: select A5:A11 and AutoFit — column A sizes to South Lamar.",
    "teach": "AutoFit Column Width (Alt, H, O, I) sizes a column to its content — a whole column fits everything in it, a selected range fits only those cells.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "3",
    "text": "The title row is cramped at the default height: from A1, set Row Height 24 points.",
    "teach": "Row Height (Alt, H, O, H) sets the selected rows’ height in points; AutoFit Row Height (Alt, H, O, A) sizes a row back to its content.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "4",
    "text": "Twenty-four was a guess: AutoFit Row Height puts row 1 back to what its one line of text needs.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "5",
    "text": "At these widths the headers B4:I4 are clipped: select them from B4, wrap the text, then AutoFit row 4 to two lines.",
    "teach": "Wrap Text (Alt, H, W) folds a long entry onto more lines inside its cell, and AutoFit Row Height then sizes the row to the wrapped lines.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "6",
    "text": "See why the day columns were set by hand: AutoFit B:G at once, read the uneven widths, then Ctrl+Z puts the equal 12 back.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "widths-heights-autofit",
    "goal_index": "7",
    "text": "Does it tie? Watch Cedar Park’s kWh in C9 change to 3,000 and the Total in C11 answer through the new widths.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "hide-group-freeze": [
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "0",
    "text": "Energy cost and Gross profit are working columns: select the whole of E:F from the header row and hide them with Ctrl+0.",
    "teach": "Ctrl+0 hides the selected columns and Ctrl+9 the rows; Ctrl+Shift+) and Ctrl+Shift+( unhide whatever is hidden inside the selection.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "1",
    "text": "A buyer’s analyst will find a hidden column and wonder what else is hidden: select D:G across the gap and unhide with Ctrl+Shift+).",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "2",
    "text": "Rows hide the same way: select the whole daily table, rows 13:21, hide them with Ctrl+9, then bring them back with Ctrl+Shift+(.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "3",
    "text": "Group, don’t hide: select the whole of E:F again and group the two working columns with Alt+Shift+→.",
    "teach": "Alt+Shift+→ groups the selected whole columns or rows into an outline with a button to fold and unfold; Alt+Shift+← ungroups them.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "4",
    "text": "Fold the group with Hide Detail, Alt A H: the two columns tuck behind an outline button instead of vanishing.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "5",
    "text": "Unfold it with Show Detail, Alt A J: the workings are there when a reader wants them, and the group stays.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "6",
    "text": "The title, units, header row and site column must stay in view: land on B5 and freeze panes there with Alt W F F.",
    "teach": "Freeze Panes (Alt W F F) pins every row above and every column left of the active cell so they stay in view as the sheet scrolls.",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "hide-group-freeze",
    "goal_index": "7",
    "text": "Does it tie? Watch Cedar Park’s kWh in C9 change to 3,000 and the Total in C11 answer, with the heads frozen in place.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ],
  "challenge-reshape-the-report": [
   {
    "lesson_id": "challenge-reshape-the-report",
    "goal_index": "0",
    "text": "The Depot site opened: insert a row inside the block, above the last site, and enter Depot, 1,800 kWh, $828 revenue, $234 energy cost.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-reshape-the-report",
    "goal_index": "1",
    "text": "Old code in column H is the old platform’s site code: delete the whole column, not just its cells.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-reshape-the-report",
    "goal_index": "2",
    "text": "The six figure columns B:G are six different widths: select them from the header row and set Column Width 12.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-reshape-the-report",
    "goal_index": "3",
    "text": "A figure column is hidden — a buyer’s analyst would find it and wonder: unhide it inside the same selection.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-reshape-the-report",
    "goal_index": "4",
    "text": "Gross profit and Avg price in E:F are working columns: group them rather than hiding them.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   },
   {
    "lesson_id": "challenge-reshape-the-report",
    "goal_index": "5",
    "text": "Freeze the panes at B4 so the title, units, header row and site column stay in view.",
    "teach": "",
    "why": "",
    "hint_stuck": ""
   }
  ]
 },
 "modules": {
  "open-and-set-up": {
   "id": "open-and-set-up",
   "name": "Open and set up",
   "objective": "Tidy the file as it arrived: tabs, gridlines, Excel Options, the QAT, the color-and-label conventions.",
   "story_beat": "The file arrived the way inherited files do. || A tab still called Sheet2, a dead half-export, no page for the report, a price buried inside a formula. Set it up to house standard first: the tab names you choose now are the names every reference carries later.",
   "page_name": "The workbook, set up to standard"
  },
  "move-and-select": {
   "id": "move-and-select",
   "name": "Move and select",
   "objective": "Jumps, never scrolls: Ctrl+Arrow, the selection set, Go To, Go To Special.",
   "story_beat": "The associate has questions about the feed. || Last row, last column, the first blank cost, the notes below the data. Answer each one by landing on the cell that holds it, and select what you will format later. Jumps, never scrolls: the mouse is for reviewing, not building.",
   "page_name": "The feed, answered"
  },
  "enter-edit-copy-fill": {
   "id": "enter-edit-copy-fill",
   "name": "Enter, edit, copy and fill",
   "objective": "The missing day, the typos, the Report skeleton, Paste Special, Find and Replace, a timeline.",
   "story_beat": "A day is missing and the figures have typos. || Airport’s Saturday never came through; management emailed the four figures. Enter them, fix the feed in place, and build the Report skeleton from Raw with the clipboard and the fill keys.",
   "page_name": "The Report skeleton"
  },
  "structure": {
   "id": "structure",
   "name": "Structure",
   "objective": "Rows and columns that keep the totals honest; widths, heights, AutoFit; hide, group, freeze.",
   "story_beat": "Cedar Park opened this week. || A sixth site row, a margin column, a stale column to remove, and a total that has to follow every edit. Then the widths, heights, groups and frozen panes that make the page readable.",
   "page_name": "The Report, reshaped"
  },
  "format": {
   "id": "format",
   "name": "Format",
   "objective": "Numbers a banker can read; fonts, fills, borders; alignment and titles; the style pass.",
   "story_beat": "Numbers a banker can read. || Thousands separators, no stray decimals, negatives in parentheses; bold totals with a top border; inputs blue with a light tint; the title centered across the page. The standard, applied once and then repeated in a single pass.",
   "page_name": "The Report, formatted"
  },
  "formulas": {
   "id": "formulas",
   "name": "Formulas",
   "objective": "SUM and its family, relative and absolute references, links across sheets, the errors and what they mean.",
   "story_beat": "Make the page live. || Every figure on the Report links to Raw and Inputs, so a corrected feed flows through without retyping. SUM and its family, anchoring with F4, links across sheets, and what each error means.",
   "page_name": "The Report, live"
  },
  "present-and-audit": {
   "id": "present-and-audit",
   "name": "Present and audit",
   "objective": "The KPI page checked, print-ready and signed off: page one of the pack.",
   "story_beat": "Sign the page off. || The buyer’s analyst opens page one first. Check the totals tie, the conventions hold, the print fits one page, and nothing is hardcoded that should not be. Then it goes in the pack.",
   "page_name": "Page one of the pack"
  },
  "project-and-assessment": {
   "id": "project-and-assessment",
   "name": "Project, assessment, test-out",
   "objective": "Build the weekly report end to end, then prove it against the clock; or test out of the chapter.",
   "story_beat": "",
   "page_name": "The weekly KPI report"
  }
 },
 "site": {
  "briefing_1_eyebrow": "The deal · 1 of 3",
  "briefing_1_title": "A company is being sold. You prepare the numbers.",
  "briefing_1_body": "Voltline runs 40 electric-car charging sites. Its owners are selling the company. || Before any buyer sees a number, someone has to make the numbers clean, consistent and checked. That is you: an analyst, someone in finance or operations, a founder. It does not matter which.",
  "briefing_2_eyebrow": "The deal · 2 of 3",
  "briefing_2_title": "It starts with this week’s site report.",
  "briefing_2_body": "It arrived the way files usually do: a tab still called Sheet2, an old export nobody deleted, a price typed inside a formula. || You will turn it into a page a buyer can trust, using the methods investment banks train their people in. One job at a time, on the real file.",
  "briefing_3_eyebrow": "The deal · 3 of 3",
  "briefing_3_title": "Every finished page goes into the data room.",
  "briefing_3_body": "A sale runs in stages. Each chapter here is one stage, and each one ends with a finished page. || The pages go into the data room: the folder buyers will read. By the end of Chapter 1, page one is in it, built by you.",
  "orientation_eyebrow": "How this place works",
  "orientation_title": "Where things are.",
  "orientation_learn": "The path. Lessons in short modules, each one job on the file. A module ends with a challenge: the same job on a fresh file, against the clock.",
  "orientation_practice": "The reps. Drills and rapid-fire with no story, and the Daily: one ninety-second sheet, the same for everyone, once a day.",
  "orientation_leaderboard": "A board for every challenge and for the Daily. Clean runs only: no help, no mouse.",
  "orientation_level": "Finishing lessons and challenges earns XP, and XP is your level, shown in the top bar. Speed earns places on the boards, not XP.",
  "orientation_fine": "Keyboard first. Sound is on at low volume from your first key; the mute is on the workspace.",
  "landing_headline_a": "Excel isn’t learned.",
  "landing_headline_b": "It’s practiced.",
  "landing_subhead": "Learn Excel the way analysts are taught — on a real sheet, one job at a time.",
  "mode_lesson": "One job at a time on a live sheet. The keys are shown the first time; the sheet is graded on where it ends up, so any correct route counts.",
  "mode_challenge": "Every module ends in a seeded, timed run on a fresh file. Pass completes the module; pro and legendary are what you come back for.",
  "mode_drill": "The same generators stripped of the story. Pars, personal bests, and a ghost of your own best run to race.",
  "mode_daily": "Ninety seconds, the same sheet for everyone, once a day. A result card built to be shared.",
  "mode_rapid": "One shortcut at a time against the clock, drawn from the ones you remember least. Recall is the game.",
  "mode_boards": "A board for every challenge and for the Daily. Clean runs only: no help, no mouse. Rank turns on when the field fills.",
  "dash_learn": "The path: chapters, modules, lessons and their challenges, one story on one file.",
  "dash_practice": "The reps: timed, no story. What is due today, the Daily, drills and rapid-fire.",
  "deal_strip_stage_1": "The data comes in",
  "deal_strip_deliverable_1": "The weekly KPI page: clean, live, formatted, checked, print-ready",
  "page_delivered": "Page {n} — {page} — delivered to the data room.",
  "save_nudge": "Your progress is saved on this device. Create a free account to keep it across devices — everything carries over.",
  "install_prompt": "Install hotkey.gg as an app. One click; it opens in its own window and stays in your dock.",
  "due_empty": "Nothing due. Play the Daily, or carry on with the next lesson.",
  "due_foot": "Short reps on what you are about to forget. Nothing is lost by skipping a day."
 }
};
