// app2/content/copy/rules.js — the vocabulary the copy checks and the screens agree on.
// RIBBON_WORDS: a goal that names one of these names something visible (R4). SITE_KEYS: the
// site.csv keys the screens read (R11 warns when one is missing; the screen keeps its built-in line).

export const RIBBON_WORDS = [
  'Ribbon', 'KeyTips?', 'Home tab', 'View tab', 'File tab', 'Format Cells', 'Rename Sheet', 'Delete Sheet', 'Move or Copy', 'Insert Sheet',
  'Go To Special', 'Go To', 'Find', 'Replace', 'Paste Special', 'Fill Series', 'AutoSum', 'AutoFit', 'Freeze Panes', 'Page Setup', 'Excel Options',
  'Quick Access Toolbar', 'QAT', 'Name Box', 'formula bar', 'Font Color', 'Gridlines', 'Bold', 'Italic', 'Underline', 'Borders?', 'Fill', 'Wrap',
  'Center Across Selection', 'Number tab', 'Increase Decimal', 'Decrease Decimal', 'Fill Color', 'Constants', 'Formulas', 'Blanks', 'Calculation', 'Automatic', 'Manual', 'Iterative', 'Alignment', 'Group', 'Ungroup', 'Hide', 'Unhide', 'Undo', 'Redo', 'Options', 'tab', 'sheet', 'row', 'column', 'header', 'title', 'total',
];

export const SITE_KEYS = [
  'briefing_1_eyebrow', 'briefing_1_title', 'briefing_1_body',
  'briefing_2_eyebrow', 'briefing_2_title', 'briefing_2_body',
  'briefing_3_eyebrow', 'briefing_3_title', 'briefing_3_body',
  'orientation_eyebrow', 'orientation_title', 'orientation_learn', 'orientation_practice', 'orientation_leaderboard', 'orientation_level', 'orientation_fine',
  'first_run_demo_title', 'first_run_demo_body', 'first_run_exp_new', 'first_run_exp_sometimes', 'first_run_exp_daily',
  'landing_headline', 'landing_subhead', 'landing_start_note', 'landing_teams_title', 'landing_teams_body', 'demo_done',
  'mode_lesson', 'mode_challenge', 'mode_drill', 'mode_daily', 'mode_rapid', 'mode_boards',
  'dash_learn', 'dash_practice',
  'deal_strip_stage_1', 'deal_strip_deliverable_1',
  'save_nudge', 'due_empty', 'due_foot', 'due_fresh',
  'tab_keys_note', 'lesson_nudge', 'lesson_nudge_help', 'lesson_show_me_playing', 'lesson_sheet_off', 'lesson_mouse',
  'lesson_done', 'lesson_done_project', 'lesson_done_verified', 'lesson_clean', 'lesson_assisted', 'page_delivered', 'lesson_first_saved', 'install_prompt',
  'times_up', 'times_up_note', 'over_limit', 'over_limit_assessment', 'review_clean', 'review_flag',
  'learn_testout', 'learn_verified', 'learn_replay',
  'drill_finished_assisted', 'drill_help_used', 'drill_mouse_used', 'drill_daily_attempt', 'rapid_intro', 'rapid_fine',
  'boards_closed', 'boards_desk_prompt', 'account_guest', 'paywall_line', 'paywall_signed_in', 'teams_desk_signin',
  // the rail, the level table and the settings table (R1b: M88, M101, M103)
  'rail_home', 'rail_learn', 'rail_practice', 'rail_daily', 'rail_drills', 'rail_rapid', 'rail_challenges', 'rail_boards', 'rail_reference',
  'rail_level', 'rail_xp', 'rail_streak', 'rail_streak_none', 'rail_go_pro', 'rail_account', 'rail_sign_in', 'rail_guest', 'rail_profile',
  'rail_settings', 'rail_billing', 'rail_certificate', 'rail_sign_out', 'rail_menu', 'rail_week_days', 'level_title_new_workbook',
  'level_title_arrow_keys', 'level_title_ctrl_arrow', 'level_title_mouse_retired', 'level_title_alt_native', 'level_title_chord_player',
  'level_title_live_links', 'level_title_ties_out', 'level_title_model_owner', 'level_title_hard_clock', 'level_title_top_bucket',
  'level_reward_themes_start', 'level_reward_theme', 'level_reward_crimson', 'level_reward_profile_frame', 'level_reward_ghost_trail',
  'level_reward_keycap_skin', 'level_reward_sound_set', 'level_reward_board_flair', 'level_reward_cursor_color', 'level_reward_panel_style',
  'level_up_title', 'level_up_reward', 'level_next', 'settings_group_keyboard', 'settings_group_lessons', 'settings_group_practice',
  'settings_group_appearance', 'settings_group_sound', 'settings_group_email', 'settings_group_account', 'setting_keyLabels',
  'setting_keyLabels_help', 'setting_keyLabels_win', 'setting_keyLabels_mac', 'setting_layout', 'setting_layout_us', 'setting_layout_uk',
  'setting_layout_other', 'setting_ribbonLessons', 'setting_ribbonLessons_help', 'setting_ribbonLessons_full', 'setting_ribbonLessons_tabs',
  'setting_ribbonDrills', 'setting_ribbonDrills_full', 'setting_ribbonDrills_tabs', 'setting_siteKeyTips', 'setting_siteKeyTips_help',
  'setting_cardSide', 'setting_cardSide_help', 'setting_cardSide_auto', 'setting_cardSide_left', 'setting_cardSide_right', 'setting_showKeys',
  'setting_showKeys_help', 'setting_showKeys_first', 'setting_showKeys_always', 'setting_nudge', 'setting_nudge_help', 'setting_nudge_8',
  'setting_nudge_15', 'setting_nudge_off', 'setting_demo', 'setting_demo_help', 'setting_setLength', 'setting_setLength_5', 'setting_setLength_10',
  'setting_setLength_20', 'setting_ghost', 'setting_ghost_help', 'setting_pace', 'setting_pace_help', 'setting_showOnBoards', 'setting_theme',
  'setting_theme_locked', 'setting_density', 'setting_density_comfortable', 'setting_density_compact', 'setting_sheetZoom', 'setting_sheetZoom_100',
  'setting_sheetZoom_110', 'setting_sheetZoom_125', 'setting_sound', 'setting_sound_help', 'setting_soundSet', 'setting_soundSet_default',
  'setting_effects', 'setting_effects_help', 'setting_effects_full', 'setting_effects_reduced', 'setting_effects_off', 'setting_dailyReminder',
  'setting_dailyReminder_help', 'setting_weeklySummary', 'setting_news', 'setting_handle', 'setting_certificateName', 'setting_certificateName_help',
  // the workspace chrome, the task card and the run panel (R1b: M90, M91, M93)
  'ws_back', 'ws_more', 'ws_sound_on', 'ws_sound_off', 'ws_goal_count', 'ws_task_count', 'ws_lesson_menu_hint', 'ws_close', 'ws_done', 'ws_esc_again', 'ws_sub_lesson',
  'ws_exit', 'ws_exit_hint', 'ws_sheet_keys', 'ws_sheet_keys_or', 'ws_full_screen', 'ws_full_screen_tip', 'ws_focus_title', 'ws_focus_where', 'ws_focus_clock', 'more_exit',
  'leave_title', 'leave_body', 'leave_run_title', 'leave_run_body', 'leave_drill_title', 'leave_action', 'leave_stay', 'card_also_works', 'card_alt_or', 'card_live_try', 'card_live_works', 'panel_exit_ends',
  'ws_sub_challenge', 'ws_sub_item', 'ws_sub_drill', 'ws_sub_daily', 'ws_sub_due', 'ws_kind_project', 'ws_kind_assessment', 'ws_kind_testout', 'more_lessons',
  'more_restart', 'more_collapse', 'more_expand', 'more_move', 'more_report', 'restart_title', 'restart_body', 'restart_action', 'dialog_cancel', 'card_help',
  'card_hide', 'card_type', 'card_live_start', 'card_live_one', 'card_live_keys', 'card_live_done', 'card_live_wrong', 'card_live_mouse', 'card_live_mouse_help',
  'card_live_watch', 'card_live_demo', 'card_live_your_turn', 'card_live_doing', 'card_help_keys', 'card_help_once', 'card_help_do', 'card_help_clean', 'card_help_assisted',
  'card_help_none', 'card_card_hidden', 'card_side_right', 'card_side_left', 'card_side_below', 'card_side_above', 'card_side_auto', 'tier_pass', 'tier_expert',
  'tier_legendary', 'tier_none', 'panel_pace', 'panel_pace_behind', 'panel_best', 'panel_tasks', 'panel_about', 'panel_minutes', 'panel_minute', 'panel_seconds',
  'panel_press_any', 'panel_ready_foot', 'panel_ready_foot_assessment', 'panel_back', 'panel_keys_so_far', 'panel_esc_ends', 'panel_done_n', 'panel_more_after',
  'panel_all_done', 'panel_tasks_done', 'panel_new_best', 'panel_new_best_first', 'drill_finished', 'panel_no_time_help', 'panel_no_time_mouse', 'panel_xp_word',
  'panel_xp', 'panel_board', 'panel_board_today', 'panel_board_up', 'panel_board_down', 'panel_board_still', 'panel_equip', 'panel_quest', 'panel_quest_done',
  'panel_times', 'panel_once', 'panel_shortcuts', 'panel_shortcuts_n', 'panel_next_lesson', 'panel_next_drill', 'panel_next_due', 'panel_back_learn', 'panel_back_home',
  'panel_all_drills', 'panel_run_again', 'panel_run_again_fresh', 'panel_see_board', 'panel_try_again', 'panel_start_job', 'panel_look_sheet', 'panel_install',
  'panel_not_now', 'panel_create_account', 'panel_goals', 'panel_limit', 'panel_sheet_off', 'panel_daily_attempts', 'panel_copy_result', 'panel_result_copied',
  'panel_copy_blocked',
  'setting_signIn', 'setting_publicProfile', 'setting_exportData', 'setting_deleteAccount', 'landing_nav_pricing', 'landing_nav_teams',
  // Home, Learn, Practice and the boards (R1b: M89, M97, M104)
  'home_next_lesson', 'home_next_assessment', 'home_resume', 'home_start', 'home_start_assessment', 'home_lesson_of', 'home_goal_of', 'home_minutes_left', 'home_all_done', 'chapter_heading', 'chapter_modules_done', 'col_module', 'col_lesson', 'col_minutes', 'col_status', 'status_complete', 'status_lessons_done', 'status_in_progress', 'status_not_started', 'status_coming', 'status_done', 'status_skipped', 'status_verified', 'status_lesson_of', 'home_level', 'home_xp', 'home_next_reward', 'home_top_level', 'home_today', 'home_today_done', 'home_refreshers', 'home_seconds', 'quests_fresh', 'home_daily_row', 'home_daily_len', 'home_daily_played', 'home_daily_played_local', 'home_daily_help', 'home_xp_plus', 'home_streak_day', 'home_achievements', 'home_count_of', 'home_ach_next', 'paywall_go_pro', 'paywall_not_now', 'learn_tab', 'learn_page_fill', 'learn_page_built', 'learn_coming', 'practice_drills', 'practice_set_line', 'practice_set_line_one', 'practice_one_minute', 'practice_minutes', 'practice_set_none', 'practice_see_set', 'practice_hide_set', 'practice_start', 'practice_chapter_fact', 'col_drill', 'col_length', 'col_best', 'practice_not_played', 'practice_after', 'practice_pro', 'practice_set_heading', 'reason_due', 'reason_slowest', 'reason_newest', 'reason_next_tier', 'reason_fill', 'daily_title', 'daily_line', 'daily_play', 'daily_pro_note', 'daily_clean_runs', 'daily_not_played', 'rapid_title', 'rapid_len_30', 'rapid_len_60', 'rapid_len_120', 'rapid_start', 'rapid_best', 'col_hits', 'col_combo', 'rapid_none', 'challenges_title', 'challenges_line', 'challenges_fact', 'challenges_start', 'boards_title', 'boards_tab_daily', 'boards_tab_drills', 'boards_tab_challenges', 'boards_tab_desks', 'col_place', 'col_player', 'col_field', 'col_time', 'col_gap', 'col_keys', 'boards_keys_route', 'boards_up', 'boards_down', 'boards_clean_runs', 'boards_day_runs', 'boards_empty', 'boards_yours', 'boards_last_five', 'boards_where', 'boards_none_yet', 'boards_signed_out', 'boards_desks_signed_out', 'boards_desk_link', 'boards_loading', 'boards_failed', 'boards_retry', 'boards_pick',
  // the first run and the coach marks (M92), the landing page and the footer (M95), the paywall and pricing (M105), Reference (M106), Settings (M101)
  'orientation_home', 'orientation_reference', 'orientation_streak', 'coach_count', 'coach_next',
  'first_run_title', 'first_run_q_keyboard', 'first_run_q_experience', 'first_run_keyboard_win', 'first_run_keyboard_mac', 'first_run_fine', 'first_run_then', 'first_run_next', 'first_run_skip', 'first_run_start',
  'landing_start', 'landing_fact_lessons', 'landing_fact_challenges', 'landing_fact_hours', 'landing_tab_start', 'landing_tab_path', 'landing_tab_drills', 'landing_tab_rapid', 'landing_tab_boards', 'landing_tab_challenges', 'landing_tab_certificate',
  'landing_path_title', 'landing_hours', 'landing_free', 'landing_pro', 'landing_path_1_title', 'landing_path_1', 'landing_path_2_title', 'landing_path_2', 'landing_path_3_title', 'landing_path_3', 'landing_path_4_title', 'landing_path_4', 'landing_path_5_title', 'landing_path_5', 'landing_path_6_title', 'landing_path_6',
  'landing_drills', 'landing_rapid', 'landing_boards', 'landing_challenges', 'landing_certificate', 'landing_pricing', 'landing_pro_price', 'landing_see_pricing', 'landing_return', 'landing_return_tail',
  'landing_demo_idle', 'landing_demo_still', 'landing_demo_focus', 'landing_demo_taken', 'landing_demo_failed',
  'landing_plate_drills_title', 'landing_plate_drills_facts', 'landing_plate_rapid_cmd', 'landing_plate_rapid_line', 'landing_plate_boards_title', 'landing_plate_boards_facts', 'landing_plate_challenges_title',
  'certificate_name', 'certificate_course', 'certificate_progress',
  'footer_pricing', 'footer_teams', 'footer_about', 'footer_contact', 'footer_privacy', 'footer_terms', 'footer_eula', 'footer_trademarks',
  'paywall_pro', 'paywall_go', 'paywall_chapter', 'paywall_this_lesson',
  'pricing_title', 'pricing_free', 'pricing_free_unit',
  'pricing_free_1', 'pricing_free_2', 'pricing_free_3', 'pricing_free_4', 'pricing_checkout_soon', 'pricing_money_back',
  'pricing_terms_title', 'pricing_term_1_name', 'pricing_term_1', 'pricing_term_2_name', 'pricing_term_2', 'pricing_term_3_name', 'pricing_term_3', 'pricing_term_4_name', 'pricing_term_4',
  'pricing_full', 'pricing_teams_col', 'pricing_recommended', 'pricing_full_figure', 'pricing_full_unit', 'pricing_full_student', 'pricing_teams_figure', 'pricing_teams_unit', 'pricing_teams_seats', 'pricing_full_1', 'pricing_full_2', 'pricing_full_3', 'pricing_full_4', 'pricing_teams_1', 'pricing_teams_2', 'pricing_teams_3', 'pricing_full_go', 'pricing_teams_go', 'pricing_teams_note', 'pricing_teams_subject', 'pricing_trust_cancel', 'pricing_trust_refund', 'pricing_trust_stripe', 'pricing_signed_in_note', 'paywall_price',
  'checkout_title', 'checkout_signin_head', 'checkout_signin_line', 'checkout_email', 'checkout_send_code', 'checkout_code', 'checkout_code_sent', 'checkout_verify', 'checkout_other_email', 'checkout_err_email', 'checkout_err_code', 'checkout_err_network', 'checkout_err_failed', 'checkout_retry', 'checkout_unavailable', 'checkout_see_pricing', 'checkout_loading', 'checkout_form_label', 'checkout_summary', 'checkout_price', 'checkout_price_student', 'checkout_inc_1', 'checkout_inc_2', 'checkout_inc_3', 'checkout_cancel', 'checkout_guarantee', 'checkout_stripe', 'checkout_have_head', 'checkout_have_line', 'checkout_done_title', 'checkout_done_wait', 'checkout_done_ok', 'checkout_done_go', 'checkout_done_timeout', 'checkout_done_support', 'checkout_done_refresh', 'checkout_done_signin', 'checkout_done_chapters', 'account_plan', 'account_plan_free', 'account_plan_full', 'account_plan_student', 'account_plan_renews', 'account_plan_ends', 'account_plan_granted', 'account_plan_granted_until', 'account_plan_free_line', 'account_cancel', 'account_manage', 'account_get', 'account_cancel_note', 'account_billing_err', 'account_billing_none',
  'ref_title', 'ref_loading', 'ref_failed', 'retry', 'ref_search', 'ref_group_move', 'ref_group_select', 'ref_group_edit', 'ref_group_format', 'ref_group_formulas', 'ref_group_ribbon', 'ref_group_data', 'ref_group_count',
  'ref_col_key', 'ref_col_what', 'ref_col_taught', 'ref_col_state', 'ref_state_not_yet', 'ref_state_taught', 'ref_state_practiced', 'ref_state_under_par', 'ref_drill_it', 'ref_or', 'ref_no_match', 'ref_collected', 'ref_drill_note',
  'settings_title', 'settings_saved_line', 'settings_not_saved', 'setting_handle_open', 'setting_signIn_open', 'setting_exportData_do', 'setting_deleteAccount_do',
];
