// app2/content/copy/rules.js — the vocabulary the copy checks and the screens agree on.
// RIBBON_WORDS: a goal that names one of these names something visible (R4). SITE_KEYS: the
// site.csv keys the screens read (R11 warns when one is missing; the screen keeps its built-in line).

export const RIBBON_WORDS = [
  'Ribbon', 'KeyTips?', 'Home tab', 'View tab', 'File tab', 'Format Cells', 'Rename Sheet', 'Delete Sheet', 'Move or Copy', 'Insert Sheet',
  'Go To Special', 'Go To', 'Find', 'Replace', 'Paste Special', 'Fill Series', 'AutoSum', 'AutoFit', 'Freeze Panes', 'Page Setup', 'Excel Options',
  'Quick Access Toolbar', 'QAT', 'Name Box', 'formula bar', 'Font Color', 'Gridlines', 'Bold', 'Italic', 'Underline', 'Borders?', 'Fill', 'Wrap',
  'Center Across Selection', 'Number tab', 'Increase Decimal', 'Decrease Decimal', 'Fill Color', 'Constants', 'Formulas', 'Blanks', 'Calculation', 'Automatic', 'Manual', 'Iterative', 'Alignment', 'Group', 'Ungroup', 'Hide', 'Unhide', 'Undo', 'Redo', 'Options', 'tab', 'sheet', 'row', 'column', 'header', 'title', 'total',
];

export const SITE_KEYS = [
  'briefing_1_eyebrow', 'briefing_1_title', 'briefing_1_body',
  'briefing_2_eyebrow', 'briefing_2_title', 'briefing_2_body',
  'briefing_3_eyebrow', 'briefing_3_title', 'briefing_3_body',
  'orientation_eyebrow', 'orientation_title', 'orientation_learn', 'orientation_practice', 'orientation_leaderboard', 'orientation_level', 'orientation_fine',
  'first_run_demo_title', 'first_run_demo_body', 'first_run_exp_new', 'first_run_exp_sometimes', 'first_run_exp_daily',
  'landing_headline', 'landing_subhead', 'landing_start_note', 'landing_teams_title', 'landing_teams_body', 'demo_done',
  'mode_lesson', 'mode_challenge', 'mode_drill', 'mode_daily', 'mode_rapid', 'mode_boards',
  'dash_learn', 'dash_practice',
  'deal_strip_stage_1', 'deal_strip_deliverable_1',
  'save_nudge', 'due_empty', 'due_foot', 'due_fresh',
  'tab_keys_note', 'lesson_nudge', 'lesson_nudge_help', 'lesson_show_me_playing', 'lesson_sheet_off', 'lesson_mouse',
  'lesson_done', 'lesson_done_project', 'lesson_done_verified', 'lesson_clean', 'lesson_assisted', 'page_delivered', 'lesson_first_saved', 'install_prompt',
  'times_up', 'times_up_note', 'over_limit', 'over_limit_assessment', 'review_clean', 'review_flag',
  'learn_testout', 'learn_verified', 'learn_replay',
  'drill_finished_assisted', 'drill_help_used', 'drill_mouse_used', 'drill_daily_attempt', 'rapid_intro', 'rapid_fine',
  'boards_closed', 'boards_desk_prompt', 'account_guest', 'paywall_line', 'paywall_signed_in', 'teams_desk_signin',
  // the rail, the level table and the settings table (R1b: M88, M101, M103)
  'rail_home', 'rail_learn', 'rail_practice', 'rail_daily', 'rail_drills', 'rail_rapid', 'rail_challenges', 'rail_boards', 'rail_reference',
  'rail_level', 'rail_xp', 'rail_streak', 'rail_streak_none', 'rail_go_pro', 'rail_account', 'rail_sign_in', 'rail_guest', 'rail_profile',
  'rail_settings', 'rail_billing', 'rail_certificate', 'rail_sign_out', 'rail_menu', 'rail_week_days', 'level_title_new_workbook',
  'level_title_arrow_keys', 'level_title_ctrl_arrow', 'level_title_mouse_retired', 'level_title_alt_native', 'level_title_chord_player',
  'level_title_live_links', 'level_title_ties_out', 'level_title_model_owner', 'level_title_hard_clock', 'level_title_top_bucket',
  'level_reward_themes_start', 'level_reward_theme', 'level_reward_crimson', 'level_reward_profile_frame', 'level_reward_ghost_trail',
  'level_reward_keycap_skin', 'level_reward_sound_set', 'level_reward_board_flair', 'level_reward_cursor_color', 'level_reward_panel_style',
  'level_up_title', 'level_up_reward', 'level_next', 'settings_group_keyboard', 'settings_group_lessons', 'settings_group_practice',
  'settings_group_appearance', 'settings_group_sound', 'settings_group_email', 'settings_group_account', 'setting_keyLabels',
  'setting_keyLabels_help', 'setting_keyLabels_win', 'setting_keyLabels_mac', 'setting_layout', 'setting_layout_us', 'setting_layout_uk',
  'setting_layout_other', 'setting_ribbonLessons', 'setting_ribbonLessons_help', 'setting_ribbonLessons_full', 'setting_ribbonLessons_tabs',
  'setting_ribbonDrills', 'setting_ribbonDrills_full', 'setting_ribbonDrills_tabs', 'setting_siteKeyTips', 'setting_siteKeyTips_help',
  'setting_cardSide', 'setting_cardSide_help', 'setting_cardSide_auto', 'setting_cardSide_left', 'setting_cardSide_right', 'setting_showKeys',
  'setting_showKeys_help', 'setting_showKeys_first', 'setting_showKeys_always', 'setting_nudge', 'setting_nudge_help', 'setting_nudge_8',
  'setting_nudge_15', 'setting_nudge_off', 'setting_demo', 'setting_demo_help', 'setting_setLength', 'setting_setLength_5', 'setting_setLength_10',
  'setting_setLength_20', 'setting_ghost', 'setting_ghost_help', 'setting_pace', 'setting_pace_help', 'setting_showOnBoards', 'setting_theme',
  'setting_theme_locked', 'setting_density', 'setting_density_comfortable', 'setting_density_compact', 'setting_sheetZoom', 'setting_sheetZoom_100',
  'setting_sheetZoom_110', 'setting_sheetZoom_125', 'setting_sound', 'setting_sound_help', 'setting_soundSet', 'setting_soundSet_default',
  'setting_effects', 'setting_effects_help', 'setting_effects_full', 'setting_effects_reduced', 'setting_effects_off', 'setting_dailyReminder',
  'setting_dailyReminder_help', 'setting_weeklySummary', 'setting_news', 'setting_handle', 'setting_certificateName', 'setting_certificateName_help',
  // the workspace chrome, the task card and the run panel (R1b: M90, M91, M93)
  'ws_back', 'ws_more', 'ws_sound_on', 'ws_sound_off', 'ws_goal_count', 'ws_task_count', 'ws_lesson_menu_hint', 'ws_close', 'ws_done', 'ws_esc_again', 'ws_sub_lesson',
  'ws_sub_challenge', 'ws_sub_item', 'ws_sub_drill', 'ws_sub_daily', 'ws_sub_due', 'ws_kind_project', 'ws_kind_assessment', 'ws_kind_testout', 'more_lessons',
  'more_restart', 'more_collapse', 'more_expand', 'more_move', 'more_report', 'restart_title', 'restart_body', 'restart_action', 'dialog_cancel', 'card_help',
  'card_hide', 'card_type', 'card_live_start', 'card_live_one', 'card_live_keys', 'card_live_done', 'card_live_wrong', 'card_live_mouse', 'card_live_mouse_help',
  'card_live_watch', 'card_live_demo', 'card_live_your_turn', 'card_live_doing', 'card_help_keys', 'card_help_once', 'card_help_do', 'card_help_clean', 'card_help_assisted',
  'card_help_none', 'card_card_hidden', 'card_side_right', 'card_side_left', 'card_side_below', 'card_side_above', 'card_side_auto', 'tier_pass', 'tier_expert',
  'tier_legendary', 'tier_none', 'panel_pace', 'panel_pace_behind', 'panel_best', 'panel_tasks', 'panel_about', 'panel_minutes', 'panel_minute', 'panel_seconds',
  'panel_press_any', 'panel_ready_foot', 'panel_ready_foot_assessment', 'panel_back', 'panel_keys_so_far', 'panel_esc_ends', 'panel_done_n', 'panel_more_after',
  'panel_all_done', 'panel_tasks_done', 'panel_new_best', 'panel_new_best_first', 'drill_finished', 'panel_no_time_help', 'panel_no_time_mouse', 'panel_xp_word',
  'panel_xp', 'panel_board', 'panel_board_today', 'panel_board_up', 'panel_board_down', 'panel_board_still', 'panel_equip', 'panel_quest', 'panel_quest_done',
  'panel_times', 'panel_once', 'panel_shortcuts', 'panel_shortcuts_n', 'panel_next_lesson', 'panel_next_drill', 'panel_next_due', 'panel_back_learn', 'panel_back_home',
  'panel_all_drills', 'panel_run_again', 'panel_run_again_fresh', 'panel_see_board', 'panel_try_again', 'panel_start_job', 'panel_look_sheet', 'panel_install',
  'panel_not_now', 'panel_create_account', 'panel_goals', 'panel_limit', 'panel_sheet_off', 'panel_daily_attempts', 'panel_copy_result', 'panel_result_copied',
  'panel_copy_blocked',
  'setting_signIn', 'setting_publicProfile', 'setting_exportData', 'setting_deleteAccount', 'landing_nav_pricing', 'landing_nav_teams',
];
