// app2/ui/sprites.js — the achievement art (screenplay 6.7, 6.7b; 3.0 "Achievements and level titles";
// M103): one hand-drawn 16 by 16 pixel object per badge, drawn at 1x and shown at 4x (64px), four
// to six colors with two or three tones of shading and a one-pixel dark outline, lit from the top
// left, on a transparent ground: no tile, circle or glow behind it. The sprite reads the same on
// every theme, so its colors are the art's own (like an image), not theme tokens; rarity is a
// colored word under the badge, never part of the art. A locked badge is the sprite's gray
// silhouette.
//
// A sprite is data: `px` is 16 rows of 16 characters, '.' transparent and every other character a
// slot in `pal`. `outline: true` adds the dark outline around the filled pixels at load, for the
// few drawn as bare shapes (the runner, the broom); every other sprite carries its outline in the
// rows. Variants (the chapter-tinted stopwatches and keyrings) reuse a drawing with a palette
// patch, which is how an artist would recolor one sprite.
//
//   SPRITES[key]                      → { pal, px }
//   spriteRows(key), spriteColours(key)
//   spriteSvg(key, { size, locked, cls, title })  → an <svg> string (crisp, one <rect> per pixel run)

/** The outline: a warm near-black, darker than any ink. */
const O = '#1d1b24';

/* the shared ramps, so a gold or a steel reads the same from badge to badge */
const GOLD = { h: '#fff1b0', y: '#f7cf4a', m: '#e0a11f', d: '#a8681a' };
const STEEL = { w: '#ffffff', l: '#d7dbe0', m: '#9aa2ad', d: '#626a77' };
const PAPER = { w: '#fffdf4', l: '#ece6d2', d: '#c3b99c' };
const WOOD = { l: '#d99a5c', m: '#a9683b', d: '#6f4124' };
const RED = { l: '#ff8a73', m: '#e2483a', d: '#9e2b26' };

/** The chapter tints for the Verified stopwatches and the keyrings: face (light) and mark (dark). */
export const CHAPTER_TINTS = [
  { f: '#ffffff', c: '#1f9d55' },   // 1 Foundations: a white face, the lesson green
  { f: '#d9e8ff', c: '#2f63b8' },   // 2 Formatting: blue
  { f: '#e8ddff', c: '#6b3fc4' },   // 3 Formulas: violet
  { f: '#ffe3c7', c: '#b8501a' },   // 4 Data and Lookups: orange
  { f: '#ffdbe8', c: '#c42b6a' },   // 5 Finance and Accounting: rose
  { f: '#fff0c2', c: '#a8681a' },   // 6 Valuation: gold
];

const STOPWATCH_TICK = [
  '......oooo......',
  '......osso......',
  '.....oooooo.....',
  '...oossssssoo...',
  '..ossffffffmmo..',
  '..oswfffffffmo..',
  '.osffffffffccmo.',
  '.osfffffffccfmo.',
  '.osfccfffccffmo.',
  '.osffccfccfffmo.',
  '.osfffcccffffmo.',
  '.osffffcfffffmo.',
  '..osffffffffmo..',
  '..ommffffffmmo..',
  '...oommmmmmoo...',
  '.....oooooo.....',
];

const KEYRING = [
  '..oooooooooooo..',
  '.occcccccccccco.',
  '.oco........oco.',
  '.occcccccccccco.',
  '..oooooooooooo..',
  '.ooo.....ooo....',
  '.oko.ooo.oko.ooo',
  '.ooo.oko.ooo.oko',
  '..K..ooo..K..ooo',
  '..K...K...K...K.',
  '..KK..K...KK..K.',
  '..K...KK..K...KK',
  '..KK..K...KK..K.',
  '......KK......KK',
  '................',
  '................',
];

const tinted = (base, n) => ({ ...base, ...CHAPTER_TINTS[n] });

export const SPRITES = {
  /* ---------- the starters (Wolf, 2026-10-02: a few easy ones, and a joke) ---------- */
  'time-card': { pal: { o: O, w: PAPER.w, l: PAPER.l, d: '#b7ad8f', r: RED.m, R: RED.d }, px: [
    '................',
    '...oooooooooo...',
    '...owwwwwwwlo...',
    '...owddddddlo...',
    '...owwwwwwwlo...',
    '...owdwdddwlo...',
    '...owwwwwwwlo...',
    '...owdwrrRwlo...',
    '...owwwrRRwlo...',
    '...owdwdddwlo...',
    '...owwwwwwwlo...',
    '...owdwdddwlo...',
    '...owwwwwwwlo...',
    '...olllllllldo..',
    '...oooooooooo...',
    '................',
  ] },
  'name-tag': { pal: { o: O, r: RED.m, R: RED.d, w: '#ffffff', d: '#7d8794', l: '#dfe3e8' }, px: [
    '................',
    '................',
    '................',
    '................',
    '.oooooooooooooo.',
    '.orrrrrrrrrrrro.',
    '.oRRRRRRRRRRRRo.',
    '.owwwwwwwwwwwlo.',
    '.owddwdddwddwlo.',
    '.owwwwwwwwwwwlo.',
    '.ollllllllllllo.',
    '.oooooooooooooo.',
    '................',
    '................',
    '................',
    '................',
  ] },
  snail: { pal: { o: O, s: '#f2a65a', S: '#c9762f', d: '#8a4a1c', g: '#b5cf9c', G: '#7fa36a' }, px: [
    '................',
    '................',
    '................',
    '.......oooo.....',
    '.....oossssoo...',
    '....ossdddssso..',
    '....osddsddsso..',
    '....osdsssdsso..',
    '.o..osddddssso..',
    '.oo.oSssssssSo..',
    '.ogo.ooSSSSoo...',
    '.oggooooooooooo.',
    '..oggggggggggGo.',
    '...ooooooooooo..',
    '................',
    '................',
  ] },

  /* ---------- the campaign: lessons, modules, chapters ---------- */
  keycap: { pal: { o: O, w: '#fffbea', l: '#efe2c2', m: '#d2bf95', d: '#a38c62' }, px: [
    '................',
    '................',
    '................',
    '...oooooooooo...',
    '..owwwwwwwwwwo..',
    '..owllllllllmo..',
    '..owllllllllmo..',
    '..owllllllllmo..',
    '..owllllllllmo..',
    '..owllllllllmo..',
    '..ommmmmmmmmmo..',
    '..odmmmmmmmmdo..',
    '..oddddddddddo..',
    '...oooooooooo...',
    '................',
    '................',
  ] },
  door: { pal: { o: O, d: WOOD.d, m: WOOD.m, l: WOOD.l, y: '#ffe9a0', g: GOLD.m }, px: [
    '................',
    '...oooooooooo...',
    '...oddddddddo...',
    '...odllmoyydo...',
    '...odlmmoyydo...',
    '...odlmmoyydo...',
    '...odllmoyydo...',
    '...odllmoyydo...',
    '...odlgmoyydo...',
    '...odllmoyydo...',
    '...odlmmoyydo...',
    '...odlmmoyydo...',
    '...odllmoyydo...',
    '...oooooooooo...',
    '........yyyyy...',
    '................',
  ] },
  compass: { pal: { o: O, w: STEEL.w, l: STEEL.l, m: STEEL.m, d: STEEL.d, r: RED.m }, px: [
    '................',
    '.....oooooo.....',
    '...oowwddwwoo...',
    '..owwwwwwwwllo..',
    '..owwwwwwwrrlo..',
    '.owwwwwwwwrrllo.',
    '.owwwwwwwrlllmo.',
    '.odwwwworlllldo.',
    '.odlllmlllllldo.',
    '.olllmllllllmo..',
    '.ollmllllllllmo.',
    '..ollllllllmmo..',
    '..olllllllmmmo..',
    '...oommddmmoo...',
    '.....oooooo.....',
    '................',
  ] },
  'pencil-cell': { pal: { o: O, e: '#f08fa0', y: GOLD.y, d: GOLD.d, g: '#1f9d55', w: '#ffffff' }, px: [
    '................',
    '.............oo.',
    '............oeeo',
    '...........oeeo.',
    '..........oydo..',
    '.........oydo...',
    '........oydo....',
    '.ggggggoydogg...',
    '.gwwwwoydowwg...',
    '.gwwwoydowwwg...',
    '.gwwoydowwwwg...',
    '.gwowwowwwwwg...',
    '.googgggggggg...',
    '.o..............',
    '................',
    '................',
  ] },
  'i-beam': { pal: { o: O, w: STEEL.w, l: STEEL.l, m: STEEL.m, d: STEEL.d }, px: [
    '................',
    '..oooooooooooo..',
    '..owwwwwwwwwwo..',
    '..oldlllllldmo..',
    '..ommmmmmmmmmo..',
    '..oooowllmoooo..',
    '.....owllmo.....',
    '.....owdlmo.....',
    '.....owllmo.....',
    '.....owllmo.....',
    '..oooowllmoooo..',
    '..owwwwwwwwwwo..',
    '..oldlllllldmo..',
    '..ommmmmmmmmdo..',
    '..oooooooooooo..',
    '................',
  ] },
  'ruled-page': { pal: { o: O, w: PAPER.w, l: PAPER.l, d: PAPER.d, b: '#5aa0e6' }, px: [
    '................',
    '...ooooooo......',
    '...owwwwwdo.....',
    '...owwwwwddo....',
    '...owwwwwoooo...',
    '...owwwwwwwlo...',
    '...owbbbbbblo...',
    '...owwwwwwwlo...',
    '...owbbbbbblo...',
    '...owwwwwwwlo...',
    '...owbbbbbblo...',
    '...owwwwwwwlo...',
    '...owoooooolo...',
    '...olllllllldo..',
    '...oooooooooo...',
    '................',
  ] },
  'equals-tile': { pal: { o: O, G: '#5ccf86', g: '#1f9d55', D: '#14683a', w: '#ffffff' }, px: [
    '................',
    '................',
    '...oooooooooo...',
    '..oGGGGGGGGGGo..',
    '..oGggggggggDo..',
    '..oGggggggggDo..',
    '..oGgwwwwwwgDo..',
    '..oGgwwwwwwgDo..',
    '..oGgDDDDDDgDo..',
    '..oGgwwwwwwgDo..',
    '..oGgwwwwwwgDo..',
    '..oGgDDDDDDgDo..',
    '..oDDDDDDDDDDo..',
    '...oooooooooo...',
    '................',
    '................',
  ] },
  'signed-page': { pal: { o: O, w: PAPER.w, l: PAPER.l, d: PAPER.d, g: '#2fb15c', G: '#17783a' }, px: [
    '................',
    '...ooooooo......',
    '...owwwwwdo.....',
    '...owwwwwddo....',
    '...owwwwwoooo...',
    '...owddddwwlo...',
    '...owwwwwwwlo...',
    '...owddddddlo...',
    '...owwwwwwwlo.gg',
    '...owdddwwwlogg.',
    '...owwwggwwlgg..',
    '...owwwwggwgg...',
    '...owwwwwGGGo...',
    '...olllllllldo..',
    '...oooooooooo...',
    '................',
  ] },
  report: { pal: { o: O, g: '#1f9d55', w: '#ffffff', d: '#9aa2ad', b: '#2f63b8', l: '#e3e7e5' }, px: [
    '................',
    '................',
    '..oooooooooooo..',
    '..oggggggggggo..',
    '..oggggggggggo..',
    '..owwwwwwwwwwo..',
    '..owdddwbbwbbo..',
    '..owwwwwwwwwwo..',
    '..owdddwbbwbbo..',
    '..owwwwwwwwwwo..',
    '..owddwwbbwbbo..',
    '..owwwwooooooo..',
    '..owdddwoowooo..',
    '..ollllllllllo..',
    '..oooooooooooo..',
    '................',
  ] },
  'stopwatch-tick': { pal: { o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff', ...CHAPTER_TINTS[0] }, px: STOPWATCH_TICK },
  stopwatch: { pal: { o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff', f: '#ffffff', c: O }, px: [
    '......oooo......',
    '......osso......',
    '.....oooooo.....',
    '...oossssssoo...',
    '..ossffffffmmo..',
    '..oswfffcfffmo..',
    '.osffffffcffffm.',
    '.osfffffcffffmo.',
    '.osfffffcffffmo.',
    '.osfffffccccfmo.',
    '.osfffffffffmo..',
    '.osffffffffffmo.',
    '..osffffffffmo..',
    '..ommffffffmmo..',
    '...oommmmmmoo...',
    '.....oooooo.....',
  ] },
  'missing-step': { pal: { o: O, l: '#eceae3', m: '#b9b5a8', d: '#7f7b70', b: '#2f63b8' }, px: [
    '................',
    '..........ooooo.',
    '..........olllo.',
    '..........ommdo.',
    '.......oooommdo.',
    '.......olblmmdo.',
    '.......ommmmmdo.',
    '....d.dommmmmdo.',
    '....d..ommmmmdo.',
    '....d.dommmmmdo.',
    'oooooooommmmmdo.',
    'olllllllmmmmmdo.',
    'ommmmmmmmmmmmdo.',
    'ooooooooooooooo.',
    '................',
    '................',
  ] },
  slab: { pal: { o: O, w: '#f1f1ec', l: '#cfd0c9', m: '#a7a89f', d: '#7c7d74' }, px: [
    '................',
    '................',
    '................',
    '................',
    '....oooooooo....',
    '...ollllllllo...',
    '..ollwwwwlllmo..',
    '.olwwllllwwllmo.',
    'ollllwwwlllllmmo',
    'oooooooooooooooo',
    'omdmmmmmdmmmmmdo',
    'oddddddddddddddo',
    'oooooooooooooooo',
    '................',
    '................',
    '................',
  ] },
  book: { pal: { o: O, d: '#1d3f7a', B: '#7fb0ff', b: '#3f78d6', p: PAPER.w, r: RED.m }, px: [
    '................',
    '...oooooooooo...',
    '...odBBBBBBpo...',
    '...odBbbbbbpo...',
    '...odBbbbbbpo...',
    '...odBppppbpo...',
    '...odBbbbbbpo...',
    '...odBbbbbbpo...',
    '...odBbbbbbpo...',
    '...odBbbbbbpo...',
    '...odBbbbbbpo...',
    '...odBbbbbbpo...',
    '...oddddddddo...',
    '...oooooorooo...',
    '........oro.....',
    '........o.o.....',
  ] },
  'ties-out': { pal: { o: O, d: '#7d8794', g: '#1f9d55', w: '#ffffff', G: '#14683a' }, px: [
    '................',
    '................',
    '................',
    '.dddd......dddd.',
    '................',
    '.dddd.oooo.dddd.',
    '.....ogwwgo.....',
    '.ddddowggwodddd.',
    '.....owggwo.....',
    '.ddddogwwgodddd.',
    '......oooo......',
    '.oooo......oooo.',
    '.GGGG......GGGG.',
    '................',
    '................',
    '................',
  ] },
  'folder-key': { pal: { o: O, h: '#ffe39a', y: '#f2c55c', Y: '#d39a32', k: STEEL.m, K: STEEL.d }, px: [
    '................',
    '................',
    '................',
    '..ooooo.........',
    '.ohhhhhoooooooo.',
    '.ohhhhhhhhhhhho.',
    '.ohyyyyyyyyyyYo.',
    '.ohykkkyyyyyyYo.',
    '.ohykykKKKKKyYo.',
    '.ohykkkyyyKKyYo.',
    '.ohyyyyyyyyyyYo.',
    '.ohyyyyyyyyyyYo.',
    '.oYYYYYYYYYYYYo.',
    '.oooooooooooooo.',
    '................',
    '................',
  ] },
  'three-pages': { pal: { o: O, w: '#ffffff', l: '#e8e2cf', m: '#cfc5a6', d: '#8d939c' }, px: [
    '................',
    '.......oooooooo.',
    '.......ommmmmmo.',
    '....oooooooodmo.',
    '....ollllllommo.',
    '.oooooooodlodmo.',
    '.owwwwwwollommo.',
    '.owddddwodlodmo.',
    '.owwwwwwollommo.',
    '.owddddwodlommo.',
    '.owwwwwwollooo..',
    '.owddddwollo....',
    '.owwwwwwooo.....',
    '.owwwwwwo.......',
    '.oooooooo.......',
    '................',
  ] },
  envelope: { pal: { o: O, d: PAPER.d, w: PAPER.w, r: RED.m, R: RED.d, l: PAPER.l }, px: [
    '................',
    '................',
    '................',
    '.oooooooooooooo.',
    '.odwwwwwwwwwwdo.',
    '.owdwwwwwwwwdwo.',
    '.owwdwwwwwwdwwo.',
    '.owwwdwrrwdwwwo.',
    '.owwwwrrrRwwwwo.',
    '.owwwwrrRRwwwwo.',
    '.owwwwwRRwwwwwo.',
    '.ollllllllllllo.',
    '.oooooooooooooo.',
    '................',
    '................',
    '................',
  ] },
  seal: { pal: { o: O, h: GOLD.h, y: GOLD.y, m: GOLD.m, d: GOLD.d, r: RED.m }, px: [
    '................',
    '.....oooooo.....',
    '...oohhhhyyoo...',
    '..ohhhyyyyyymo..',
    '..ohhyddddyymo..',
    '.ohhydhhyydyymo.',
    '.ohyydhyyydymmo.',
    '.ohyydyyymdymmo.',
    '.oyyydymmmdmmdo.',
    '..oyymddddmmdo..',
    '..oymmmmmmmddo..',
    '...ooddddddoo...',
    '....oooooooo....',
    '...orro..orro...',
    '..orro....orro..',
    '..o..o....o..o..',
  ] },
  'verified-1': { pal: tinted({ o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff' }, 0), px: STOPWATCH_TICK },
  'verified-2': { pal: tinted({ o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff' }, 1), px: STOPWATCH_TICK },
  'verified-3': { pal: tinted({ o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff' }, 2), px: STOPWATCH_TICK },
  'verified-4': { pal: tinted({ o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff' }, 3), px: STOPWATCH_TICK },
  'verified-5': { pal: tinted({ o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff' }, 4), px: STOPWATCH_TICK },
  'verified-6': { pal: tinted({ o: O, s: STEEL.l, m: STEEL.m, w: '#ffffff' }, 5), px: STOPWATCH_TICK },

  /* ---------- clean runs ---------- */
  'clean-cell': { pal: { y: GOLD.y, w: '#ffffff', g: '#1f9d55', l: '#e3e7e5' }, px: [
    '................',
    '............y...',
    '............y...',
    '..........yywyy.',
    '............y...',
    '............y...',
    '.gggggggggg.....',
    '.gwwwwwwwwg.....',
    '.gwwwwwwwwg.....',
    '.gwwwwwwwlg.....',
    '.gwwwwwwllg.....',
    '.gwwwwwlllg.....',
    '.ggggggggggg....',
    '..........gg....',
    '................',
    '................',
  ] },
  'no-mouse': { pal: { o: O, w: '#ffffff', l: STEEL.l, m: STEEL.m, r: RED.m, R: RED.d }, px: [
    '................',
    '.............rR.',
    '......oooo..rR..',
    '....oowwolorR...',
    '....owwwolrR....',
    '....owwwmrRo....',
    '....oooorRoo....',
    '....owlrRlmo....',
    '....owrRllmo....',
    '....orRlllmo....',
    '....rRllllmo....',
    '...rRlllllmo....',
    '..rR.ommmmo.....',
    '.rR...oooo......',
    '................',
    '................',
  ] },
  glove: { pal: { o: O, w: '#ffffff', l: '#d7dbe0', m: '#9aa2ad', d: '#626a77' }, px: [
    '................',
    '......oo.oo.....',
    '...ooowwowwooo..',
    '..owlowlowlowlo.',
    '..owlowlowlowlo.',
    '..owlowlowlowlo.',
    '..owlowlowlowlo.',
    '..owwwwwwwwwwlo.',
    '.oowwwwwwwwwwlo.',
    'owwwwwwwwwwwwlo.',
    'olwwwwwwwwwwllo.',
    '.oowwwwwwwwwllo.',
    '.oooooooooooooo.',
    '.ommmmmmmmmmmdo.',
    '.oooooooooooooo.',
    '................',
  ] },

  /* ---------- drills, bests and tiers ---------- */
  target: { pal: { o: O, r: RED.m, R: RED.d, w: '#ffffff' }, px: [
    '................',
    '.....oooooo.....',
    '...oorrrrrroo...',
    '..orrwwwwwwrRo..',
    '..orwwrrrrwwRo..',
    '.orwwrrrrrrwwRo.',
    '.orwrrwwwwrrwRo.',
    '.orwrrwrrwrrwRo.',
    '.orwrrwrRwrRwRo.',
    '.orwrrwwwwrRwRo.',
    '.orwwrrrrRRwwRo.',
    '..orwwRRRRwwRo..',
    '..orRwwwwwwRRo..',
    '...ooRRRRRRoo...',
    '.....oooooo.....',
    '................',
  ] },
  suitcase: { pal: { o: O, B: WOOD.l, b: WOOD.m, d: WOOD.d, s: '#f7cf4a', r: '#3fae9e' }, px: [
    '................',
    '................',
    '................',
    '......oooo......',
    '......o..o......',
    '..oooooooooooo..',
    '..oBdBBBBBBdBo..',
    '..oBdbbbbbbddo..',
    '..oBdbssbbbddo..',
    '..oBdbssbbbddo..',
    '..oBdbbbrrbddo..',
    '..oBdbbbrrbddo..',
    '..oddddddddddo..',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  board: { pal: { o: O, y: GOLD.y, Y: GOLD.m, w: '#ffffff', d: '#b9c0c8', l: '#e3e7e5' }, px: [
    '................',
    '................',
    '................',
    '..oooooooooooo..',
    '..oYyyyyyyyyYo..',
    '..oYYYYYYYYYYo..',
    '..owwwwwwwwwwo..',
    '..owddddwwwdwo..',
    '..owwwwwwwwwwo..',
    '..owddddwwwdwo..',
    '..owwwwwwwwwwo..',
    '..ollllllllllo..',
    '..oooooooooooo..',
    '.....oo..oo.....',
    '.....oo..oo.....',
    '................',
  ] },
  medals: { pal: { o: O, r: RED.m, R: RED.d, w: GOLD.h, y: GOLD.y, Y: GOLD.d }, px: [
    '................',
    '................',
    '................',
    '.....ooooo......',
    '.....orrRo......',
    'oooooorrRoooooo.',
    'orrRo.oRo.orrRo.',
    'orrRo.ooo.orrRo.',
    '.oRo.owyYo.oRo..',
    '.ooo.oyyYo.ooo..',
    'owyYooyYYoowyYo.',
    'oyyYo.ooo.oyyYo.',
    'oyYYo.....oyYYo.',
    '.ooo.......ooo..',
    '................',
    '................',
  ] },
  'keyring-1': { pal: { o: O, k: STEEL.w, K: STEEL.d, c: CHAPTER_TINTS[0].c }, px: KEYRING },
  'keyring-2': { pal: { o: O, k: STEEL.w, K: STEEL.d, c: CHAPTER_TINTS[1].c }, px: KEYRING },
  'keyring-3': { pal: { o: O, k: STEEL.w, K: STEEL.d, c: CHAPTER_TINTS[2].c }, px: KEYRING },
  'keyring-4': { pal: { o: O, k: STEEL.w, K: STEEL.d, c: CHAPTER_TINTS[3].c }, px: KEYRING },
  'keyring-5': { pal: { o: O, k: STEEL.w, K: STEEL.d, c: CHAPTER_TINTS[4].c }, px: KEYRING },
  'keyring-6': { pal: { o: O, k: STEEL.w, K: STEEL.d, c: CHAPTER_TINTS[5].c }, px: KEYRING },
  'green-light': { pal: { o: O, B: '#5b616b', b: '#3a3d45', d: '#24272d', g: '#5ee37a', G: '#22a046' }, px: [
    '....oooooooo....',
    '....oBbbbbbo....',
    '....oBbddbbo....',
    '....oBddddbo....',
    '....oBbddbbo....',
    '....oBbbbbbo....',
    '....oBbddbbo....',
    '....oBddddbo....',
    '....oBbddbbo....',
    '....oBbbbbbo....',
    '....oBbggbbo....',
    '....oBgggGbo....',
    '....oBbGGbbo....',
    '....oBbbbbbo....',
    '....oooooooo....',
    '.......oo.......',
  ] },
  'gem-blue': { pal: { o: O, w: '#ffffff', h: '#9cd0ff', m: '#3f86e0', d: '#244f9e', x: '#16306b' }, px: [
    '................',
    '................',
    '................',
    '................',
    '....oooooooo....',
    '...owhhmhhmdo...',
    '..ohhhmhhhmmdo..',
    '.oooooooooooooo.',
    '..ohhmmmmmddxo..',
    '...ohmmmmddxo...',
    '....ohmmmdxo....',
    '.....ohmdxo.....',
    '......omdo......',
    '.......oo.......',
    '................',
    '................',
  ] },
  'gem-gold': { pal: { o: O, w: '#fffbe0', h: GOLD.h, m: GOLD.y, d: GOLD.m, x: GOLD.d }, px: [
    '................',
    '.............w..',
    '............www.',
    '.............w..',
    '....oooooooo....',
    '...owhhmhhmdo...',
    '..ohhhmhhhmmdo..',
    '.oooooooooooooo.',
    '..ohhmmmmmddxo..',
    '...ohmmmmddxo...',
    '....ohmmmdxo....',
    '.....ohmdxo.....',
    '......omdo......',
    '.......oo.......',
    '................',
    '................',
  ] },
  flame: { pal: { o: O, R: RED.m, r: '#ef7d22', Y: GOLD.y, y: GOLD.h, d: RED.d }, px: [
    '................',
    '......o.........',
    '.....oRo....o...',
    '..o..oRo...oRo..',
    '.oRo.oRRo..oRo..',
    '.oRRooRrRooRRo..',
    '.oRRRRrrRRRRRo..',
    '.oRRrrrrrrrRRo..',
    '.oRrrrYYrrrrRo..',
    '.oRrrYYYYrrrRo..',
    '.oRrYYyyYYrrRo..',
    '.oRrYyyyyYrRdo..',
    '..oRrYyyYrRdo...',
    '...oRrrrrRddo...',
    '....oddddddo....',
    '.....oooooo.....',
  ] },
  crown: { pal: { o: O, h: GOLD.h, y: GOLD.y, m: GOLD.m, d: GOLD.d, r: RED.m }, px: [
    '................',
    '................',
    '................',
    '..o....oo....o..',
    '.oho..ohyo..oyo.',
    '.ohyoohyymooymo.',
    '.ohyyhyyyymyymo.',
    '.ohyyyyyyyyyymo.',
    '.oooooooooooooo.',
    '.ohyryyrryyrymo.',
    '.ohyyyyyyyyyymo.',
    '.ommmmmmmmmmmdo.',
    '.oooooooooooooo.',
    '................',
    '................',
    '................',
  ] },

  /* ---------- the Daily and streaks ---------- */
  'calendar-day': { pal: { o: O, r: RED.m, w: '#ffffff', d: '#b9c0c8', x: '#e07a2e', l: '#e3e7e5' }, px: [
    '................',
    '....o......o....',
    '..oooooooooooo..',
    '..orrrrrrrrrro..',
    '..orrrrrrrrrro..',
    '..owwwwwwwwwwo..',
    '..owdwdwdwdwdo..',
    '..owwwwwwwwwwo..',
    '..owdwdwxxwdwo..',
    '..owwwwwxxwwwo..',
    '..owdwdwdwdwdo..',
    '..owwwwwwwwwwo..',
    '..ollllllllllo..',
    '..oooooooooooo..',
    '................',
    '................',
  ] },
  'calendar-week': { pal: { o: O, r: RED.m, w: '#ffffff', x: '#e07a2e', l: '#e3e7e5' }, px: [
    '................',
    '................',
    '................',
    '..o..o..o..o..o.',
    '.ooooooooooooooo',
    '.orrrrrrrrrrrrro',
    '.orrrrrrrrrrrrro',
    '.owwwwwwwwwwwwwo',
    '.oxwxwxwxwxwxwxo',
    '.oxwxwxwxwxwxwxo',
    '.owwwwwwwwwwwwwo',
    '.olllllllllllllo',
    '.ooooooooooooooo',
    '................',
    '................',
    '................',
  ] },
  'calendar-month': { pal: { o: O, r: RED.m, w: '#ffffff', x: '#e07a2e', l: '#e3e7e5' }, px: [
    '....o......o....',
    '..oooooooooooo..',
    '..orrrrrrrrrro..',
    '..orrrrrrrrrro..',
    '..owwwwwwwwwwo..',
    '..owxwxwxwxwxo..',
    '..owwwwwwwwwwo..',
    '..owxwxwxwxwxo..',
    '..owwwwwwwwwwo..',
    '..owxwxwxwxwxo..',
    '..owwwwwwwwwwo..',
    '..owxwxwxwxwxo..',
    '..owwwwwwwwwwo..',
    '..ollllllllllo..',
    '..oooooooooooo..',
    '................',
  ] },
  runner: { outline: true, pal: { o: O, h: '#e8b98a', b: '#3f86e0', k: '#3a3d45', w: '#ffffff' }, px: [
    '................',
    '..........hh....',
    '..........hh....',
    '.........h......',
    '.......bbbb.....',
    '......b.bb.b....',
    '.....b.bb...h...',
    '....h..bb.......',
    '.......kk.......',
    '......k..k......',
    '.....k....k.....',
    '...wk.....k.....',
    '..........ww....',
    '................',
    '................',
    '................',
  ] },

  /* ---------- efficiency ---------- */
  'key-star': { pal: { o: O, y: GOLD.y, w: '#fffbea', l: '#efe2c2', m: '#d2bf95', d: '#a38c62' }, px: [
    '................',
    '.......o........',
    '......oyo.......',
    '....ooywyoo.....',
    '......oyo.......',
    '.......o........',
    '................',
    '...oooooooooo...',
    '..owwwwwwwwwwo..',
    '..owllllllllmo..',
    '..owllllllllmo..',
    '..owllllllllmo..',
    '..ommmmmmmmmmo..',
    '..oddddddddddo..',
    '...oooooooooo...',
    '................',
  ] },
  abacus: { pal: { o: O, B: WOOD.l, b: WOOD.m, r: RED.m, R: RED.d, k: STEEL.m }, px: [
    '................',
    '................',
    '.oooooooooooooo.',
    '.oBBBBBBBBBBBbo.',
    '.oboooooooooobo.',
    '.obrRrRkkkkrRbo.',
    '.ob..........bo.',
    '.ob..........bo.',
    '.obrRkkkkrRrRbo.',
    '.ob..........bo.',
    '.ob..........bo.',
    '.obrRrRrRkkkkbo.',
    '.oboooooooooobo.',
    '.obbbbbbbbbbbbo.',
    '.oooooooooooooo.',
    '................',
  ] },

  /* ---------- rapid-fire ---------- */
  bolt: { pal: { o: O, y: GOLD.h, Y: GOLD.y, m: GOLD.m }, px: [
    '................',
    '.........oooo...',
    '........oyyYo...',
    '.......oyyYo....',
    '......oyyYo.....',
    '.....oyyYooooo..',
    '....oyyyyyyyYo..',
    '....ooooyyyYo...',
    '.......oyyYo....',
    '......oyyYo.....',
    '.....oyYmo......',
    '....oyYmo.......',
    '...oYmo.........',
    '..omo...........',
    '..oo............',
    '................',
  ] },
  'bolt-burst': { pal: { o: O, y: GOLD.h, Y: GOLD.y, m: GOLD.m, q: '#de3f7d' }, px: [
    '..q.............',
    '...q.....oooo..q',
    '........oyyYo.q.',
    '.......oyyYo....',
    '......oyyYo.....',
    '.....oyyYooooo..',
    'qq..oyyyyyyyYo..',
    '....ooooyyyYo.qq',
    '.......oyyYo....',
    '......oyyYo.....',
    '.....oyYmo......',
    '....oyYmo....q..',
    '...oYmo.......q.',
    '..omo...........',
    '.qoo............',
    'q...............',
  ] },
  chain: { pal: { o: O, l: STEEL.l, m: STEEL.m, d: STEEL.d }, px: [
    '................',
    '................',
    '................',
    '................',
    '.oooo......oooo.',
    'olllmo....olllmo',
    'ol..oooooooo..mo',
    'ol..lllllllm..mo',
    'ol..oooooooo..mo',
    'ommmdo....ommmdo',
    '.oooo......oooo.',
    '................',
    '................',
    '................',
    '................',
    '................',
  ] },
  'bolt-ring': { pal: { o: O, q: '#de3f7d', y: GOLD.h, Y: GOLD.y, m: GOLD.m }, px: [
    '................',
    '.....oooooo.....',
    '...ooqqqqqqoo...',
    '..oq....ooo.qo..',
    '..oq...oyYo.qo..',
    '.oq...oyYooo.qo.',
    '.oq..oyyyyYo.qo.',
    '.oq..oooyYo..qo.',
    '.oq...oyYo...qo.',
    '.oq..oymo....qo.',
    '.oq.omo......qo.',
    '..oqoo......qo..',
    '..oq........qo..',
    '...ooqqqqqqoo...',
    '.....oooooo.....',
    '................',
  ] },

  /* ---------- quests ---------- */
  scroll: { pal: { o: O, l: PAPER.l, d: PAPER.d, p: PAPER.w, r: RED.m, R: RED.d }, px: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..oooooooooooo..',
    '.oldppprRppldo..',
    '.odlpprRRrppldo.',
    '.odlpprRRrppldo.',
    '.oldppprRpppldo.',
    '..oooooooooooo..',
    '.......rR.......',
    '......r..R......',
    '................',
    '................',
    '................',
  ] },
  scrolls: { pal: { o: O, d: PAPER.d, p: PAPER.w, r: RED.m }, px: [
    '................',
    '................',
    '................',
    '................',
    '.....ooooo......',
    '....odpprpo.....',
    '....odpprpo.....',
    '.....ooooo......',
    '..ooooo.ooooo...',
    '.odpprpodpprpo..',
    '.odpprpodpprpo..',
    '..ooooo.ooooo...',
    '................',
    '................',
    '................',
    '................',
  ] },
  broom: { outline: true, bare: 'l', pal: { o: O, b: WOOD.m, r: RED.m, y: GOLD.y, Y: GOLD.m, l: '#9aa2ad' }, px: [
    '................',
    '.............b..',
    '............b...',
    '...........b....',
    '..........b.....',
    '.........b......',
    '........b.......',
    '......rrr.......',
    '.....rrrr.......',
    '....yyyYy.......',
    '...yyYyyY.lll...',
    '..yyYyyYy.......',
    '..yYyyYyY..llll.',
    '..YyY.yY........',
    '................',
    '................',
  ] },

  /* ---------- volume and levels ---------- */
  ledger: { pal: { o: O, w: '#ffffff', g: '#7cc79a', l: '#e3e7e5', b: '#1d6b45' }, px: [
    '................',
    '................',
    '................',
    '.oooooo..oooooo.',
    'owwwwwwoowwwwwwo',
    'owwgwgwoowgwgwwo',
    'ollglglooglglllo',
    'owwgwgwoowgwgwwo',
    'ollglglooglglllo',
    'owwgwgwoowgwgwwo',
    'ollglglooglglllo',
    'owwwwwwoowwwwwwo',
    'oooooooooooooooo',
    'obbbbbbbbbbbbbbo',
    '.oooooooooooooo.',
    '................',
  ] },
  candle: { pal: { o: O, y: GOLD.h, Y: GOLD.y, r: '#ef7d22', w: PAPER.w, l: PAPER.l }, px: [
    '................',
    '.......o........',
    '......oyo.......',
    '.....oyYro......',
    '.....oYYro......',
    '......oro.......',
    '.......o........',
    '.....oooooo.....',
    '.....owwwlo.....',
    '.....owwwlo.....',
    '.....owwwlo.....',
    '.....owwwlo.....',
    '.....owwwlo.....',
    '.....owwllo.....',
    '.....oooooo.....',
    '................',
  ] },
  campfire: { pal: { o: O, R: RED.m, r: '#ef7d22', Y: GOLD.y, y: GOLD.h, b: WOOD.m }, px: [
    '................',
    '.......o........',
    '......oRo..o....',
    '..o...oRo.oRo...',
    '.oRo.oRrRooRo...',
    '.oRRooRrrRRRo...',
    '.oRrrrrYrrRRo...',
    '.oRrrYYYYrRRo...',
    '..oRrYyyYrRo....',
    '...oRrYYrRo.....',
    '..oooooooooooo..',
    '.oYbbbbbbbbbbYo.',
    '.oooooooooooooo.',
    '..oYbbbbbbbbYo..',
    '..oooooooooooo..',
    '................',
  ] },
  'pepper-mill': { pal: { o: O, k: STEEL.l, K: STEEL.m, B: WOOD.l, b: WOOD.m, d: WOOD.d }, px: [
    '................',
    '.......oo.......',
    '......okKo......',
    '.....oooooo.....',
    '.....oBbbdo.....',
    '.....oBbbdo.....',
    '......oBdo......',
    '.....oBbbdo.....',
    '....oBBbbbdo....',
    '....oBbbbbdo....',
    '....oBbbbbdo....',
    '.....oBbbdo.....',
    '.....oBbbdo.....',
    '.....okkKKo.....',
    '.....oooooo.....',
    '................',
  ] },
  bucket: { pal: { o: O, R: '#ff7a6b', r: '#c8323a', d: '#82202a', y: GOLD.y, Y: GOLD.m }, px: [
    '................',
    '.....oooooo.....',
    '....o......o....',
    '...o........o...',
    '..oooooooooooo..',
    '..oRRRRRRRRRRo..',
    '..orrrrrrrrrdo..',
    '...orrryyrrdo...',
    '...oryyyyyydo...',
    '...orrYyyYrdo...',
    '...oryyrryydo...',
    '...orrrrrrrdo...',
    '...orrrrrrddo...',
    '....oddddddo....',
    '....oooooooo....',
    '................',
  ] },

  /* ---------- the hidden ones ---------- */
  eye: { pal: { o: O, w: '#ffffff', l: '#d7dbe0', b: '#3f86e0', B: '#1d3f7a' }, px: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '...oowwwwwwoo...',
    '..owwwbbbbwwlo..',
    '.owwwbwoobBwwlo.',
    '.olwwbbooBBwllo.',
    '..ollwbBBBwllo..',
    '...oollllllooo..',
    '.....oooooo.....',
    '................',
    '................',
    '................',
  ] },
  'moon-monitor': { pal: { o: O, y: GOLD.y, k: '#3a3d45', c: '#7fd3ff', C: '#3f86e0' }, px: [
    '..oo............',
    '.oyo....y.......',
    'oyo.........y...',
    'oyo.............',
    '.oyo.oooooooooo.',
    '..oo.okkkkkkkko.',
    '.....okccccccko.',
    '.....okCCCcccko.',
    '.....okccccccko.',
    '.....okCCcCCcko.',
    '.....okccccccko.',
    '.....okkkkkkkko.',
    '.....oooooooooo.',
    '........okko....',
    '......oooooooo..',
    '................',
  ] },
  sunrise: { pal: { o: O, y: GOLD.h, Y: GOLD.y, r: '#ef7d22' }, px: [
    '................',
    '................',
    '.......yy.......',
    '..y....yy....y..',
    '...y........y...',
    '................',
    '.....oooooo.....',
    '...ooyyyyyyoo...',
    '..oyYYYYYYYYro..',
    '.oyYYYYYYYYYrro.',
    '.oYYYYYYYYYrrro.',
    'oooooooooooooooo',
    '..rr..rrrr..rr..',
    '................',
    '................',
    '................',
  ] },
  hammock: { pal: { o: O, b: WOOD.m, s: '#3f86e0', S: '#ffffff', d: '#7fa36a' }, px: [
    '................',
    '................',
    'ooo..........ooo',
    'obo..........obo',
    'oboo........oobo',
    'obo.o......o.obo',
    'obo..osSsSo..obo',
    'obo..oSsSso..obo',
    'obo...oooo...obo',
    'obo..........obo',
    'obo..........obo',
    'obo..........obo',
    'obo..........obo',
    'ooo..........ooo',
    'dddddddddddddddd',
    '................',
  ] },
  'cracked-mouse': { pal: { o: O, w: '#ffffff', l: STEEL.l, m: STEEL.m }, px: [
    '................',
    '................',
    '......oooo......',
    '....oowwoloo....',
    '....owwwollo....',
    '....owwwmllo....',
    '....oooooooo....',
    '....owllolmo....',
    '....owlollmo....',
    '....owllolmo....',
    '....owlollmo....',
    '....ololllmo....',
    '.....ommmmo.....',
    '......oooo......',
    '................',
    '................',
  ] },
};

/* ---------------- pure helpers ---------------- */

/** The rows of a sprite, with its outline added when it is drawn bare. Throws on a malformed sprite. */
export function spriteRows(key) {
  const s = SPRITES[key];
  if (!s) throw new Error('no sprite ' + key);
  const rows = s.px.map(r => String(r));
  if (rows.length !== 16 || rows.some(r => r.length !== 16)) throw new Error(`sprite ${key} must be 16 rows of 16`);
  if (!s.outline) return rows;
  const bare = new Set(String(s.bare || ''));
  const grid = rows.map(r => r.split(''));
  const filled = (x, y) => y >= 0 && y < 16 && x >= 0 && x < 16 && rows[y][x] !== '.' && !bare.has(rows[y][x]);
  for (let y = 0; y < 16; y++) for (let x = 0; x < 16; x++) {
    if (rows[y][x] !== '.') continue;
    if (filled(x - 1, y) || filled(x + 1, y) || filled(x, y - 1) || filled(x, y + 1)) grid[y][x] = 'o';
  }
  return grid.map(r => r.join(''));
}

/** The distinct colors a sprite uses (transparency aside). */
export function spriteColours(key) {
  const pal = SPRITES[key].pal;
  return [...new Set(spriteRows(key).join('').replace(/\./g, '').split('').map(ch => pal[ch]))];
}

/** The silhouette's gray: the locked badge (3.0: a locked badge is its gray silhouette). */
export const LOCKED_FILL = 'var(--line)';

/**
 * A sprite as an inline <svg>: one rect per horizontal run of a color (crisp edges, no blur at
 * any size). `locked` paints every pixel one gray. Unknown keys render nothing.
 */
export function spriteSvg(key, { size = 64, locked = false, cls = '', title = '' } = {}) {
  if (!SPRITES[key]) return '';
  const rows = spriteRows(key);
  const pal = SPRITES[key].pal;
  const rects = [];
  for (let y = 0; y < 16; y++) {
    let x = 0;
    while (x < 16) {
      const ch = rows[y][x];
      if (ch === '.') { x++; continue; }
      let w = 1;
      while (x + w < 16 && rows[y][x + w] === ch) w++;
      rects.push(`<rect x="${x}" y="${y}" width="${w}" height="1" fill="${locked ? LOCKED_FILL : pal[ch]}"/>`);
      x += w;
    }
  }
  const label = title ? `<title>${String(title).replace(/[<&>]/g, '')}</title>` : '';
  return `<svg class="sprite${cls ? ' ' + cls : ''}" width="${size}" height="${size}" viewBox="0 0 16 16" shape-rendering="crispEdges" ${title ? 'role="img"' : 'aria-hidden="true"'}>${label}${rects.join('')}</svg>`;
}
